"""fn-123.5 / R13 — print-then-ask read-back contract (canonical prose only).

Skills that show a draft/diff for approval must print the FULL markdown as an
ordinary assistant message FIRST, then issue a SHORT AskUserQuestion. This
file keeps the contract tokens, the ordering (print before ask), and the
negative guards against the old embed-drafts-in-ask-bodies wording.

Prose-quality pins removed 2026-08-07 - judged via .flow/criteria.md G1, not grep.

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is intentionally not asserted here.

Pin shape (agent_docs/adding-skills.md, "Prose-contract tests — pin content +
reachability"): the contract tokens are pinned at whichever file in the skill
carries them, plus the routing that keeps that file on the agent's load path
from `SKILL.md`. A token that moves from `workflow.md` into a routed reference
is not a regression; a token that disappears, or lands in a file nothing routes
to, is. The forbidden-embed sweep stays whole-corpus (a negative by
construction), and the §4 ordering assertions below stay position-pinned
because ordering IS the contract there.
"""

from __future__ import annotations

import pathlib
import re
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

CAPTURE_SKILL = SKILLS / "flow-next-capture" / "SKILL.md"
CAPTURE_WORKFLOW = SKILLS / "flow-next-capture" / "workflow.md"
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
INTERVIEW_DOC_AWARE = (
    SKILLS / "flow-next-interview" / "references" / "doc-aware.md"
)
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-interview" / "references" / "write-back.md"
)

ALL_FILES = (
    CAPTURE_SKILL,
    CAPTURE_WORKFLOW,
    CAPTURE_PHASES,
    INTERVIEW_DOC_AWARE,
    INTERVIEW_WRITE_BACK,
)

# Old embed-in-body wording that made long drafts unreadable — must be gone.
# (Negative guards kept: embedding drafts in ask bodies is the dangerous class.)
FORBIDDEN_EMBED_PHRASES = (
    # Capture Phase 4 old ask body that listed every criterion inside the question.
    "Full draft in the Write render above (expand if collapsed)",
    "Every acceptance criterion's substance, one short plain line each",
    "the user must see what they are approving inside the question",
    # Interview decision-entry old allowance (explicit R13 target).
    "inline in the question or in the message preceding",
    "Show the full body inline in the question",
    # Old capture overview that put the summary payload / criteria in the ask.
    "the `AskUserQuestion` body carries the plain-language summary payload",
    "every criterion in one plain line",
    # fn-123 review hardening additions.
    "the question body must say the full draft is in the Write render above",
    "rides in the §4.2 question body",
)


SPINE = "SKILL.md"


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def _corpus(skill_dir: pathlib.Path) -> dict[str, str]:
    """Every markdown file a skill ships, keyed by path relative to the skill."""
    return {
        p.relative_to(skill_dir).as_posix(): p.read_text(encoding="utf-8")
        for p in sorted(skill_dir.rglob("*.md"))
        if p.is_file()
    }


def _reachable(corpus: dict[str, str]) -> set[str]:
    """Files reachable from `SKILL.md` by following file mentions (BFS)."""
    seen = {SPINE}
    queue = [SPINE]
    while queue:
        text = corpus[queue.pop()]
        for rel in corpus:
            if rel in seen:
                continue
            if rel in text or rel.rsplit("/", 1)[-1] in text:
                seen.add(rel)
                queue.append(rel)
    return seen


CAPTURE_CORPUS = _corpus(SKILLS / "flow-next-capture")
CAPTURE_REACHABLE = _reachable(CAPTURE_CORPUS)
INTERVIEW_CORPUS = _corpus(SKILLS / "flow-next-interview")
INTERVIEW_REACHABLE = _reachable(INTERVIEW_CORPUS)


class ReadbackAskContract(unittest.TestCase):
    """Print-then-ask tokens present; old long-question embed wording absent."""

    def setUp(self) -> None:
        for path in ALL_FILES:
            self.assertTrue(path.is_file(), f"missing canonical file: {path}")
        self.capture_skill = _read(CAPTURE_SKILL)
        self.capture_workflow = _read(CAPTURE_WORKFLOW)
        self.capture_phases = _read(CAPTURE_PHASES)
        self.doc_aware = _read(INTERVIEW_DOC_AWARE)
        self.write_back = _read(INTERVIEW_WRITE_BACK)
        self.combined = "\n".join(
            (
                self.capture_skill,
                self.capture_workflow,
                self.capture_phases,
                self.doc_aware,
                self.write_back,
            )
        )

    def _assert_reachable(
        self,
        corpus: dict[str, str],
        reachable: set[str],
        predicate,
        what: str,
        skill: str,
    ) -> str:
        """`what` is stated in some file of `skill` that `SKILL.md` reaches."""
        hits = [rel for rel, text in corpus.items() if predicate(text)]
        self.assertTrue(
            hits,
            f"no file in {skill} states {what} — scanned {sorted(corpus)}",
        )
        reachable_hits = [rel for rel in hits if rel in reachable]
        self.assertTrue(
            reachable_hits,
            f"{skill}: {what} only lives in unreachable file(s) {hits} — "
            f"nothing on the path from {SPINE} carries it",
        )
        return reachable_hits[0]

    def test_contract_tokens_present_in_owning_files(self) -> None:
        """The print-then-ask tokens stay stated and reachable in each skill.

        Capture's spine additionally has to carry or route to the contract:
        the branch is decided on the always-loaded file, so `SKILL.md` either
        names print-then-ask itself or names the file that does.
        """
        contract_home = self._assert_reachable(
            CAPTURE_CORPUS,
            CAPTURE_REACHABLE,
            lambda text: "print-then-ask" in text.lower(),
            "the print-then-ask contract",
            "capture",
        )
        capture_skill = CAPTURE_CORPUS[SPINE]
        self.assertTrue(
            "print-then-ask" in capture_skill.lower()
            or contract_home in capture_skill,
            f"capture {SPINE} must state print-then-ask or route to "
            f"{contract_home}, which does",
        )
        interview_home = self._assert_reachable(
            INTERVIEW_CORPUS,
            INTERVIEW_REACHABLE,
            lambda text: "print-then-ask" in text.lower(),
            "the print-then-ask contract",
            "interview",
        )
        self.assertIn(
            interview_home,
            INTERVIEW_CORPUS[SPINE],
            f"interview {SPINE} must route to {interview_home}, which carries "
            f"the print-then-ask contract",
        )
        # Short-ask tally token stays somewhere capture routes to.
        self._assert_reachable(
            CAPTURE_CORPUS,
            CAPTURE_REACHABLE,
            lambda text: "[inferred]" in text,
            "the short-ask source tally token `[inferred]`",
            "capture",
        )
        # Edit-cycle reprint token. Branch-disclosure (fn-169) rewrote
        # capture's §4 recap with the hyphenated spelling ("Edit cycles
        # re-print the revised draft before each short ask") and moved the
        # unhyphenated copy into references/manual-smoke.md. Same contract,
        # both spellings accepted, either home.
        for skill, corpus, reachable in (
            ("capture", CAPTURE_CORPUS, CAPTURE_REACHABLE),
            ("interview", INTERVIEW_CORPUS, INTERVIEW_REACHABLE),
        ):
            with self.subTest(skill=skill):
                self._assert_reachable(
                    corpus,
                    reachable,
                    lambda text: re.search(r"re-?print", text, re.IGNORECASE)
                    is not None,
                    "the edit-cycle reprint rule",
                    skill,
                )

    def test_old_embed_in_body_wording_absent(self) -> None:
        for phrase in FORBIDDEN_EMBED_PHRASES:
            with self.subTest(phrase=phrase):
                self.assertNotIn(
                    phrase,
                    self.combined,
                    f"old embed-in-ask-body wording still present: {phrase!r}",
                )

    def test_autofix_path_still_non_interactive(self) -> None:
        """Autofix remains non-interactive; `--yes` is still the consent
        substitute — stated wherever capture documents the mode (the spine,
        `workflow.md`, or `references/autofix-mode.md`) and reachable from
        `SKILL.md`."""
        for token in ("mode:autofix", "--yes"):
            with self.subTest(token=token):
                self._assert_reachable(
                    CAPTURE_CORPUS,
                    CAPTURE_REACHABLE,
                    lambda text, token=token: token in text,
                    f"the autofix token {token!r}",
                    "capture",
                )
        self._assert_reachable(
            CAPTURE_CORPUS,
            CAPTURE_REACHABLE,
            lambda text: re.search(
                r"(?i)autofix.*--yes|`--yes`.*substitut", text
            )
            is not None,
            "the `--yes`-substitutes-for-consent rule",
            "capture",
        )


class TestPrintThenAskOrdering(unittest.TestCase):
    """fn-123 review hardening: assert ORDER, not just token presence.

    The §4.1 contract is a numbered sequence: print the full draft FIRST,
    then the short ask. Ordering keys on the smallest tokens (FULL draft /
    AskUserQuestion) inside the owning contract block.
    """

    def setUp(self) -> None:
        self.workflow = _read(CAPTURE_WORKFLOW)

    def _contract_block(self) -> str:
        start = self.workflow.find("Print-then-ask contract")
        self.assertGreater(
            start, -1, "capture workflow lost the print-then-ask contract block"
        )
        return self.workflow[start : start + 2500]

    def test_print_precedes_ask_in_contract_block(self) -> None:
        block = self._contract_block()
        print_pos = block.find("FULL draft")
        self.assertGreater(print_pos, -1, "contract lost the print-first step")
        # The ask step's AskUserQuestion mention must come AFTER the print step
        # (the intro sentence may mention the tool earlier; the step ordering is
        # what the fn-123 hardening guards).
        ask_pos = block.find("AskUserQuestion", print_pos)
        self.assertGreater(ask_pos, -1, "contract lost the short-ask step")


if __name__ == "__main__":
    unittest.main()
