"""Pre-flight gate + prose-contract tests for Codex implementation-delegation (fn-55.2).

The host-side pre-flight gates (platform gate + recursion guard) ship as runnable
bash inside ``references/codex-delegation.md``. They are pure shell predicates, so
this test EXTRACTS the two gate functions from the reference and EXECUTES them
under controlled env — the load-bearing acceptance criterion is that delegation
stays ELIGIBLE when ``CODEX_SANDBOX=auto`` is exported (Ralph's review-backend
knob) and that the recursion guard trips on a Codex RUNTIME value (e.g.
``seatbelt``) but not on ``auto``.

It also locks the prose contract — the progressive-disclosure value-check and the
disambiguation-from-the-review-backend tokens — across the canonical Claude
``SKILL.md`` / ``phases.md`` / reference (the Codex mirror is regenerated by
``sync-codex.sh`` in fn-55.6; this task ships the canonical side only).
"""

from __future__ import annotations

import os
import pathlib
import re
import shutil
import subprocess
import sys
import unittest

# Gate-relevant env keys the tests control. We SCRUB these from the inherited OS
# env so only the per-test overrides decide eligibility — while keeping the rest
# of the env (PATH, and on Windows Git-bash SYSTEMROOT/WINDIR) so bash and the
# gate's `env | grep` actually run. A bare custom env strips those and breaks
# bash on Windows (every gate test fails rc=1). `OPENCODE_*` is matched by prefix.
_GATE_ENV_KEYS = (
    "AUTONOMOUS",
    "CLAUDECODE",
    "CODEX_SANDBOX",
    "CODEX_SANDBOX_NETWORK_DISABLED",
    "DROID_PLUGIN_ROOT",
    "FLOW_AUTONOMOUS",
    "FLOW_RALPH",
    "OPENCODE",
    "REVIEW_RECEIPT_PATH",
)


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
WORK_SKILL = REPO_ROOT / "plugins" / "flow-next" / "skills" / "flow-next-work"
SKILL_MD = WORK_SKILL / "SKILL.md"
CODEX_SKILL_MD = (
    REPO_ROOT
    / "plugins"
    / "flow-next"
    / "codex"
    / "skills"
    / "flow-next-work"
    / "SKILL.md"
)
PHASES_MD = WORK_SKILL / "phases.md"
REFERENCE_MD = WORK_SKILL / "references" / "codex-delegation.md"
SELECTION_MD = WORK_SKILL / "references" / "codex-delegation-selection.md"


def _extract_bash_func(text: str, func_name: str) -> str:
    """Pull a ``name() { ... }`` bash function body out of a fenced code block.

    The reference authors each gate as a shell function inside a ```bash fence.
    We extract by brace-matching from the function header so the test executes
    the EXACT shipped definition, not a paraphrase.
    """
    start = text.find(f"{func_name}() {{")
    if start == -1:
        raise AssertionError(f"bash function {func_name!r} not found in reference")
    depth = 0
    i = text.index("{", start)
    body_start = i
    while i < len(text):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return f"{func_name}() {text[body_start:i + 1]}"
        i += 1
    raise AssertionError(f"unbalanced braces extracting {func_name!r}")


def _extract_work_argument_block(text: str) -> str:
    """Return the host-substitution slot, which must remain outside shell."""
    start_marker = "<work-arguments>\n"
    end_marker = "\n</work-arguments>"
    start = text.find(start_marker)
    if start == -1:
        raise AssertionError("literal work-arguments block not found")
    start += len(start_marker)
    end = text.find(end_marker, start)
    if end == -1:
        raise AssertionError("literal work-arguments block is unterminated")
    return text[start:end]


def _strip_standalone_autonomous_token(raw: str) -> tuple[int, str]:
    """Executable oracle for the prompt's literal, whitespace-token contract."""
    pattern = re.compile(r"(?<!\S)mode:autonomous(?!\S)")
    matches = list(pattern.finditer(raw))
    result = raw
    for match in reversed(matches):
        start, end = match.span()
        if end < len(result) and result[end].isspace():
            end += 1
        elif start > 0 and result[start - 1].isspace():
            start -= 1
        result = result[:start] + result[end:]
    return (1 if matches else 0), result


class WorkArgumentLiteralContract(unittest.TestCase):
    """The host expands raw skill arguments once; Work must keep them out of shell."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.skills = {
            "canonical": SKILL_MD.read_text(encoding="utf-8"),
            "codex": CODEX_SKILL_MD.read_text(encoding="utf-8"),
        }

    def test_argument_placeholder_is_literal_data_not_shell_input(self) -> None:
        for label, skill in self.skills.items():
            with self.subTest(host=label):
                self.assertEqual(_extract_work_argument_block(skill), "$ARGUMENTS")
                autonomy = skill.split(
                    "## Autonomous Mode (questions off, no receipt obligations)", 1
                )[1].split("## Input", 1)[0]
                self.assertNotIn("for ARG in $ARGUMENTS", autonomy)
                self.assertIn("literal prompt data", autonomy)
                self.assertIn("never shell", autonomy)
                self.assertIn("preserve\nall else verbatim", autonomy)
                self.assertIn("spaces/quotes/globs", autonomy)

    def test_glob_and_spaces_survive_host_substitution_and_strip(self) -> None:
        cases = (
            (
                "handle *.md files mode:autonomous",
                1,
                "handle *.md files",
            ),
            (
                '"handle *.md files" mode:autonomous',
                1,
                '"handle *.md files"',
            ),
            (
                "preserve  repeated spaces and [abc]*.md",
                0,
                "preserve  repeated spaces and [abc]*.md",
            ),
            (
                "mode:autonomous handle *.md files",
                1,
                "handle *.md files",
            ),
        )
        for label, skill in self.skills.items():
            for raw, expected_mode, expected_args in cases:
                with self.subTest(host=label, raw=raw):
                    rendered = skill.replace("$ARGUMENTS", raw)
                    self.assertEqual(_extract_work_argument_block(rendered), raw)
                    self.assertEqual(
                        _strip_standalone_autonomous_token(raw),
                        (expected_mode, expected_args),
                    )

    def test_embedded_autonomy_text_is_not_a_mode_token(self) -> None:
        raw = "document mode:autonomous-like behavior in *.md"
        self.assertEqual(_strip_standalone_autonomous_token(raw), (0, raw))


@unittest.skipUnless(shutil.which("bash"), "bash required to execute gate predicates")
@unittest.skipIf(
    sys.platform == "win32",
    "POSIX-shell gate predicates: the host agent runs them under Git-bash, but "
    "executing the extracted multi-line predicate via a Python subprocess + a "
    "constructed env on the Windows runner tests bash plumbing, not gate logic. "
    "Fully exercised on macOS + ubuntu; the prose-contract tests run on Windows.",
)
class CodexDelegationGateExecution(unittest.TestCase):
    """Execute the shipped gate predicates under controlled env."""

    @classmethod
    def setUpClass(cls) -> None:
        # Normalize line endings to LF. On Windows the .md checks out CRLF (no
        # .gitattributes pins it to LF), so the extracted bash function would
        # carry trailing \r and `bash -c` fails to parse it ("syntax error near
        # unexpected token `{'") — every gate-execution test then returns
        # non-zero. Stripping \r makes the extracted predicate pure LF.
        cls.ref_text = (
            REFERENCE_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        skill_text = (
            SKILL_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        cls.skill_text = skill_text
        codex_skill_text = (
            CODEX_SKILL_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        cls.codex_skill_text = codex_skill_text
        cls.platform_fn = _extract_bash_func(cls.ref_text, "platform_gate_ok")
        cls.recursion_fn = _extract_bash_func(cls.ref_text, "not_inside_codex_sandbox")
        cls.ref_headless_fn = _extract_bash_func(
            cls.ref_text, "delegation_headless"
        )
        selection_text = (
            SELECTION_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        cls.selection_headless_fn = _extract_bash_func(
            selection_text, "delegation_headless"
        )
        # The cheap Phase 0 host short-circuit lives in phases.md/SKILL.md (it must
        # resolve delegation OFF on a non-Claude host BEFORE the reference is read,
        # so it cannot live in the reference itself). Extract + execute the shipped
        # phases.md copy.
        phases_text = (
            PHASES_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        cls.host_fn = _extract_bash_func(phases_text, "host_is_claude_code")

    def _run_script(self, script: str, env: dict) -> subprocess.CompletedProcess[str]:
        """Run shipped shell text under a controlled gate-relevant environment."""
        # Start from a clean env so only the keys we set are present.
        # Inherit the OS env (PATH for bash + env/grep; SYSTEMROOT/WINDIR on
        # Windows Git-bash) but scrub every gate-relevant key first, then apply
        # the per-test overrides — so the env stays controlled without stripping
        # the vars bash needs to start.
        full_env = {
            k: v
            for k, v in os.environ.items()
            if k not in _GATE_ENV_KEYS and not k.startswith("OPENCODE_")
        }
        full_env.update(env)
        return subprocess.run(
            ["bash", "-c", f"set -u\n{script}\n"],
            env=full_env,
            capture_output=True,
            text=True,
        )

    def _run(self, func_def: str, call: str, env: dict) -> int:
        """Source the extracted function, call it, return its exit code."""
        return self._run_script(f"{func_def}\n{call}", env).returncode

    # ── Platform gate (rc 0 = eligible) ────────────────────────────────────

    def test_platform_gate_eligible_on_claude_code(self) -> None:
        rc = self._run(self.platform_fn, "platform_gate_ok", {"CLAUDECODE": "1"})
        self.assertEqual(rc, 0, "Claude Code (CLAUDECODE set, no Droid/OpenCode) must be eligible")

    # ── Phase 0 cheap host short-circuit (rc 0 = Claude Code = eligible) ────
    # The pre-LOAD gate: delegation must resolve OFF on a non-Claude host BEFORE
    # the ~45k reference is read into context (not just after, via Gate 1).

    def test_host_short_circuit_eligible_on_claude_code(self) -> None:
        rc = self._run(self.host_fn, "host_is_claude_code", {"CLAUDECODE": "1"})
        self.assertEqual(rc, 0, "Claude Code host must pass the cheap Phase 0 check")

    def test_host_short_circuit_off_without_claudecode(self) -> None:
        # The case this change targets: work.delegate=codex set, but work runs IN
        # Codex — CLAUDECODE unset → cheap check fails → reference never loaded.
        rc = self._run(self.host_fn, "host_is_claude_code", {})
        self.assertNotEqual(
            rc, 0, "non-Claude host (no CLAUDECODE) must short-circuit OFF pre-load"
        )

    def test_host_short_circuit_off_on_droid(self) -> None:
        rc = self._run(
            self.host_fn,
            "host_is_claude_code",
            {"CLAUDECODE": "1", "DROID_PLUGIN_ROOT": "/some/droid/root"},
        )
        self.assertNotEqual(rc, 0, "Droid must short-circuit OFF pre-load")

    def test_host_short_circuit_off_on_opencode(self) -> None:
        rc = self._run(
            self.host_fn, "host_is_claude_code", {"CLAUDECODE": "1", "OPENCODE": "1"}
        )
        self.assertNotEqual(rc, 0, "OpenCode must short-circuit OFF pre-load")

    def test_host_short_circuit_eligible_with_codex_sandbox_auto(self) -> None:
        # Ralph's review-backend knob must not flip the cheap host check.
        rc = self._run(
            self.host_fn,
            "host_is_claude_code",
            {"CLAUDECODE": "1", "CODEX_SANDBOX": "auto"},
        )
        self.assertEqual(
            rc, 0, "CODEX_SANDBOX=auto (Ralph knob) must leave the cheap host check ELIGIBLE"
        )

    def test_platform_gate_eligible_with_codex_sandbox_auto(self) -> None:
        # The load-bearing Ralph case: CODEX_SANDBOX=auto is the review-backend
        # knob, NOT a Codex-orchestrator signal. Platform gate must NOT exclude on it.
        rc = self._run(
            self.platform_fn,
            "platform_gate_ok",
            {"CLAUDECODE": "1", "CODEX_SANDBOX": "auto"},
        )
        self.assertEqual(
            rc, 0, "CODEX_SANDBOX=auto (Ralph knob) must leave the platform gate ELIGIBLE"
        )

    def test_platform_gate_off_without_claudecode(self) -> None:
        rc = self._run(self.platform_fn, "platform_gate_ok", {})
        self.assertNotEqual(rc, 0, "Missing CLAUDECODE → not Claude Code → ineligible")

    def test_platform_gate_off_on_droid(self) -> None:
        rc = self._run(
            self.platform_fn,
            "platform_gate_ok",
            {"CLAUDECODE": "1", "DROID_PLUGIN_ROOT": "/some/droid/root"},
        )
        self.assertNotEqual(rc, 0, "DROID_PLUGIN_ROOT set → Droid → ineligible")

    def test_platform_gate_off_on_opencode(self) -> None:
        rc = self._run(
            self.platform_fn,
            "platform_gate_ok",
            {"CLAUDECODE": "1", "OPENCODE": "1"},
        )
        self.assertNotEqual(rc, 0, "bare OPENCODE marker → ineligible")

    def test_platform_gate_off_on_prefixed_opencode_markers(self) -> None:
        # "AND no OpenCode marker" must cover arbitrary OPENCODE_* markers, not
        # just a fixed two-var check — OPENCODE_SESSION / OPENCODE_ROOT etc.
        for marker in ("OPENCODE_SESSION", "OPENCODE_ROOT", "OPENCODE_BIN"):
            with self.subTest(marker=marker):
                rc = self._run(
                    self.platform_fn,
                    "platform_gate_ok",
                    {"CLAUDECODE": "1", marker: "1"},
                )
                self.assertNotEqual(
                    rc, 0, f"{marker} (OpenCode marker) → ineligible"
                )

    # ── Recursion guard (rc 0 = NOT inside a sandbox = eligible) ────────────

    def test_recursion_guard_eligible_when_unset(self) -> None:
        rc = self._run(self.recursion_fn, "not_inside_codex_sandbox", {})
        self.assertEqual(rc, 0, "No CODEX_SANDBOX → not inside a sandbox → eligible")

    def test_recursion_guard_eligible_with_codex_sandbox_auto(self) -> None:
        # The load-bearing Ralph case again, on the recursion guard this time.
        rc = self._run(
            self.recursion_fn,
            "not_inside_codex_sandbox",
            {"CODEX_SANDBOX": "auto"},
        )
        self.assertEqual(
            rc, 0, "CODEX_SANDBOX=auto (config knob) must NOT trip the recursion guard"
        )

    def test_recursion_guard_eligible_with_config_set_values(self) -> None:
        for val in ("read-only", "workspace-write", "danger-full-access", "auto"):
            with self.subTest(value=val):
                rc = self._run(
                    self.recursion_fn,
                    "not_inside_codex_sandbox",
                    {"CODEX_SANDBOX": val},
                )
                self.assertEqual(
                    rc, 0, f"CODEX_SANDBOX={val} is in the flow-next config set → not a sandbox"
                )

    def test_recursion_guard_trips_on_runtime_value(self) -> None:
        rc = self._run(
            self.recursion_fn,
            "not_inside_codex_sandbox",
            {"CODEX_SANDBOX": "seatbelt"},
        )
        self.assertNotEqual(
            rc, 0, "CODEX_SANDBOX=seatbelt (Codex runtime value) must trip the recursion guard"
        )

    def test_recursion_guard_trips_on_network_disabled(self) -> None:
        rc = self._run(
            self.recursion_fn,
            "not_inside_codex_sandbox",
            {"CODEX_SANDBOX_NETWORK_DISABLED": "1"},
        )
        self.assertNotEqual(
            rc, 0, "CODEX_SANDBOX_NETWORK_DISABLED set must trip the recursion guard"
        )

    # ── Consent/ask marker family (rc 0 = no-question path) ────────────────

    def test_consent_ask_sites_share_the_exact_headless_predicate(self) -> None:
        self.assertEqual(self.selection_headless_fn, self.ref_headless_fn)

    def test_direct_autonomous_token_materializes_marker_before_consent(self) -> None:
        for label, skill in (
            ("canonical", self.skill_text),
            ("codex", self.codex_skill_text),
        ):
            with self.subTest(host=label):
                mode, work_args = _strip_standalone_autonomous_token(
                    "fn-145 mode:autonomous delegate:codex"
                )
                self.assertIn("Set/export `AUTONOMOUS=1`", skill)
                proc = self._run_script(
                    "\n".join(
                        (
                            f"AUTONOMOUS={mode}",
                            f"WORK_ARGS={work_args!r}",
                            self.selection_headless_fn,
                            '[ "$AUTONOMOUS" = "1" ]',
                            '[ "$WORK_ARGS" = "fn-145 delegate:codex" ]',
                            "bash -c 'test \"$AUTONOMOUS\" = 1'",
                            "delegation_headless",
                        )
                    ),
                    {},
                )
                self.assertEqual(
                    proc.returncode,
                    0,
                    f"{label} direct token must suppress consent: {proc.stderr}",
                )

    def test_interactive_parse_preserves_consent_question_path(self) -> None:
        mode, work_args = _strip_standalone_autonomous_token(
            "fn-145 delegate:codex"
        )
        proc = self._run_script(
            "\n".join(
                (
                    f"AUTONOMOUS={mode}",
                    f"WORK_ARGS={work_args!r}",
                    self.selection_headless_fn,
                    '[ "$AUTONOMOUS" = "0" ]',
                    '[ "$WORK_ARGS" = "fn-145 delegate:codex" ]',
                    "! delegation_headless",
                )
            ),
            {},
        )
        self.assertEqual(
            proc.returncode,
            0,
            f"ordinary direct invocation must remain interactive: {proc.stderr}",
        )

    def test_flow_autonomous_env_materializes_same_marker(self) -> None:
        mode, work_args = _strip_standalone_autonomous_token(
            "fn-145 delegate:codex"
        )
        proc = self._run_script(
            "\n".join(
                (
                    f"AUTONOMOUS={mode}",
                    f"WORK_ARGS={work_args!r}",
                    '[[ "${FLOW_AUTONOMOUS:-}" == "1" ]] && AUTONOMOUS=1',
                    "export AUTONOMOUS",
                    self.selection_headless_fn,
                    '[ "$AUTONOMOUS" = "1" ]',
                    "delegation_headless",
                )
            ),
            {"FLOW_AUTONOMOUS": "1"},
        )
        self.assertEqual(
            proc.returncode,
            0,
            f"FLOW_AUTONOMOUS must reach the same no-question path: {proc.stderr}",
        )

    def test_each_autonomous_marker_suppresses_consent_questions(self) -> None:
        cases = (
            ("ralph", {"FLOW_RALPH": "1"}),
            ("receipt", {"REVIEW_RECEIPT_PATH": "/tmp/review-receipt.json"}),
            ("autonomous_env", {"FLOW_AUTONOMOUS": "1"}),
            ("parsed_autonomous_token", {"AUTONOMOUS": "1"}),
        )
        for label, env in cases:
            with self.subTest(marker=label):
                rc = self._run(
                    self.selection_headless_fn, "delegation_headless", env
                )
                self.assertEqual(rc, 0, f"{label} must select the no-question path")

    def test_empty_or_zero_flags_remain_interactive(self) -> None:
        cases = (
            ("no_markers", {}),
            ("empty_markers", {
                "FLOW_RALPH": "",
                "REVIEW_RECEIPT_PATH": "",
                "FLOW_AUTONOMOUS": "",
                "AUTONOMOUS": "",
            }),
            ("zero_flags", {
                "FLOW_RALPH": "0",
                "FLOW_AUTONOMOUS": "0",
                "AUTONOMOUS": "0",
            }),
        )
        for label, env in cases:
            with self.subTest(marker=label):
                rc = self._run(
                    self.selection_headless_fn, "delegation_headless", env
                )
                self.assertNotEqual(
                    rc, 0, f"{label} must preserve interactive consent"
                )


class CodexDelegationProseContract(unittest.TestCase):
    """Lock the progressive-disclosure + disambiguation prose contract."""

    @classmethod
    def setUpClass(cls) -> None:
        for p in (SKILL_MD, PHASES_MD, REFERENCE_MD):
            assert p.exists(), f"missing required file: {p}"
        cls.skill = SKILL_MD.read_text(encoding="utf-8")
        cls.phases = PHASES_MD.read_text(encoding="utf-8")
        cls.selection = SELECTION_MD.read_text(encoding="utf-8")
        cls.ref = REFERENCE_MD.read_text(encoding="utf-8")

    def test_reference_exists_with_preflight_section(self) -> None:
        self.assertIn("Host pre-flight gates", self.ref)
        # Section stubs for the downstream tasks must be present (scaffold contract).
        self.assertIn("fn-55.3", self.ref)
        self.assertIn("fn-55.4", self.ref)
        self.assertIn("fn-55.5", self.ref)

    def test_phases_default_path_adds_single_value_check(self) -> None:
        # The one cheap value-check is the only thing added to the default path.
        self.assertIn("config get work.delegate", self.phases)
        # And it is explicitly framed as the ONLY added step.
        self.assertRegex(self.phases, r"ONLY step|single step|byte-identical")

    def test_skill_disambiguates_delegate_token_from_review_backend(self) -> None:
        for token in ("delegate:codex", "delegate:local", "work.delegate=codex"):
            with self.subTest(token=token):
                self.assertIn(token, self.skill)
        # Must state bare "use codex" stays the review backend (not delegation).
        self.assertIn("use codex", self.skill)
        self.assertRegex(self.skill, r"review backend|review-backend")

    def test_skill_points_to_reference(self) -> None:
        self.assertIn("references/codex-delegation.md", self.skill)
        self.assertIn("references/codex-delegation.md", self.phases)

    def test_phase0_host_short_circuit_documented(self) -> None:
        # Delegation is Claude-Code-only and the cheap Phase 0 check must gate
        # delegation_requested so the reference is NEVER read on a non-Claude host
        # (Codex / Droid / OpenCode). Both host skill files carry the check, ANDed
        # into the predicate; the reference header states it is not read there.
        for src in (self.phases, self.skill):
            self.assertIn("host_is_claude_code", src)
            self.assertRegex(src, r"host_is_claude_code\s*&&")
            self.assertIn("delegation_requested", src)
        self.assertIn("Off, unavailable, or declined paths never read this file", self.ref)

    def test_reference_load_waits_for_completed_selection(self) -> None:
        selection_read = self.phases.index(
            "references/codex-delegation-selection.md"
        )
        active_read = self.phases.index(
            "`references/codex-delegation.md`", selection_read
        )
        self.assertLess(selection_read, active_read)
        self.assertIn("delegation_active=true", self.selection)
        self.assertIn("reads no active reference", self.selection)

    def test_cold_selection_router_preserves_decline_and_unavailable_behavior(self) -> None:
        for contract in (
            "DROID_PLUGIN_ROOT",
            "OPENCODE_",
            "danger-full-access|auto",
            "CODEX_SANDBOX_NETWORK_DISABLED",
            "codex not found",
            "yolo (Recommended)",
            "work.delegateConsent",
            "work.delegateSandbox",
            "git status --porcelain",
            "Headless",
        ):
            with self.subTest(contract=contract):
                self.assertIn(contract, self.selection)

    def test_active_reference_owns_complete_delegation_contract(self) -> None:
        for heading in (
            "Host pre-flight gates",
            "The prompt template",
            "Safety — git-ownership enforcement",
            "Host circuit breaker",
            "Ralph-safe",
        ):
            with self.subTest(heading=heading):
                self.assertIn(heading, self.ref)

    def test_common_phases_only_keep_circuit_breaker_router(self) -> None:
        self.assertIn("already-loaded delegation reference", self.phases)
        self.assertNotIn("case DELEGATION_ACTION:", self.phases)
        self.assertNotIn("consecutive_failures += 1", self.phases)

    def test_input_bare_prompt_capture_documented(self) -> None:
        self.assertIn("INPUT_WAS_BARE_PROMPT", self.phases)
        self.assertIn("INPUT_WAS_BARE_PROMPT", self.ref)

    def test_consent_lives_in_host_not_worker(self) -> None:
        # Consent must be in the host-owned selection reference and the active
        # reference must retain its defense-in-depth contract.
        self.assertIn("AskUserQuestion", self.selection)
        self.assertIn("work.delegateConsent", self.selection)
        self.assertIn("work.delegateSandbox", self.selection)
        # The "#12890/#34592" worker-cant-ask rationale is preserved.
        self.assertIn("#12890", self.ref)

    def test_platform_gate_not_keyed_on_codex_env(self) -> None:
        # The reference must explicitly warn NOT to exclude on CODEX_* and call
        # out that CODEX_SANDBOX=auto is the review-backend knob.
        self.assertRegex(self.ref, r"Do NOT exclude on .?CODEX_\*")
        self.assertIn("CODEX_SANDBOX=auto", self.ref)

    def test_recursion_guard_config_set_documented(self) -> None:
        # The flow-next config set must be enumerated so the runtime-vs-config
        # distinction is unambiguous.
        for mode in ("read-only", "workspace-write", "danger-full-access", "auto"):
            with self.subTest(mode=mode):
                self.assertIn(mode, self.ref)
        self.assertIn("CODEX_SANDBOX_NETWORK_DISABLED", self.ref)

    def test_full_headless_consent_rule_documented_at_every_ask_site(self) -> None:
        # Every consent/per-task ask site shares the complete marker family.
        for source in (self.selection, self.ref):
            with self.subTest(source="selection" if source is self.selection else "active"):
                for marker in (
                    "FLOW_RALPH",
                    "REVIEW_RECEIPT_PATH",
                    "FLOW_AUTONOMOUS",
                    "AUTONOMOUS",
                    "mode:autonomous",
                ):
                    self.assertIn(marker, source)
                self.assertIn("delegation_headless", source)
                self.assertRegex(source, r"standard (?:in-session )?Work")
                self.assertRegex(source, r"no config write|Do not write")

    def test_delegate_decision_semantics_documented(self) -> None:
        self.assertIn("work.delegateDecision", self.ref)
        self.assertIn("auto", self.ref)
        self.assertIn("ask", self.ref)
        self.assertIn("delegation_headless", self.ref)


if __name__ == "__main__":
    unittest.main()
