"""Prose-contract test for fn-68.2 — tracker-sync autonomous-safe parity +
the enumeration method + the async question-valve anchor contract.

fn-68.2 makes the tracker-sync skill safe to call **per-tick from
`/flow-next:pilot` backlog mode** and supplies the surface backlog mode needs:

  R14 — Phase-0 autonomy parity: the gate recognizes the full marker family
        (`FLOW_AUTONOMOUS` / `mode:autonomous`), not just `FLOW_RALPH` /
        `REVIEW_RECEIPT_PATH`, so no per-tick path reaches `AskUserQuestion`.
  R15 — the async question-valve: a stable `<!-- flow-next:question id=<hash>
        status=open|answered -->` anchor (id hashes STABLE fields only, prose
        outside the hash, no bare tracker key), a flat-tracker
        `<!-- flow-next:answer id=<hash> -->` fallback matched by id, and the
        9th adapter method `listOpenIssues(filter) → issue[]` (exact-match
        readyState lane, Linear + GitHub) + the named skill ops `list-open` /
        `question`.
  R16 — reuses the existing status-sync readyState→ready projection (no new
        mechanism — asserted by absence of a *second* projection mechanism).

This is a **prose contract** test: fn-68.2 ships skill prose + adapter-reference
docs (the host agent IS the runtime — there is no Python engine to unit-test).
The test locks the load-bearing invariants the agentic skill must carry so a
later edit can't silently drop them.

**Canonical Claude files ONLY.** The Codex mirror
(`plugins/flow-next/codex/skills/flow-next-tracker-sync/`) is regenerated by
`sync-codex.sh` in the SEPARATE task fn-68.5 — it does NOT yet carry the fn-68
additions, so asserting against it here would be wrong (and would fail). The
mirror's contract is fn-68.5's to lock.

Run:
    python3 -m unittest plugins.flow-next.tests.test_tracker_sync_backlog_mode -v
"""

from __future__ import annotations

import pathlib
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
SKILL_DIR = (
    REPO_ROOT
    / "plugins"
    / "flow-next"
    / "skills"
    / "flow-next-tracker-sync"
)
STEPS = SKILL_DIR / "steps.md"
SKILL = SKILL_DIR / "SKILL.md"
ADAPTER_IFACE = SKILL_DIR / "references" / "adapter-interface.md"
COMMENTS_SYNC = SKILL_DIR / "references" / "comments-sync.md"
GITHUB = SKILL_DIR / "references" / "github.md"
LINEAR_GRAPHQL = SKILL_DIR / "references" / "linear-graphql.md"
LINEAR_LADDER = SKILL_DIR / "references" / "linear-ladder.md"
LINEAR_MCP = SKILL_DIR / "references" / "linear-mcp.md"
DOCS = REPO_ROOT / "plugins" / "flow-next" / "docs" / "tracker-sync.md"

# The Codex mirror — asserted to EXIST but deliberately NOT asserted to carry
# the fn-68 content (that is fn-68.5's regen, a separate task).
CODEX_STEPS = (
    REPO_ROOT
    / "plugins"
    / "flow-next"
    / "codex"
    / "skills"
    / "flow-next-tracker-sync"
    / "steps.md"
)


def _read(p: pathlib.Path) -> str:
    return p.read_text(encoding="utf-8")


class TrackerSyncBacklogModeProseContract(unittest.TestCase):
    """Lock the fn-68.2 invariants in the canonical Claude skill files."""

    @classmethod
    def setUpClass(cls) -> None:
        for p in (
            STEPS,
            SKILL,
            ADAPTER_IFACE,
            COMMENTS_SYNC,
            GITHUB,
            LINEAR_GRAPHQL,
            LINEAR_LADDER,
            LINEAR_MCP,
            DOCS,
        ):
            assert p.exists(), f"required canonical file missing: {p}"
        cls.steps = _read(STEPS)
        cls.skill = _read(SKILL)
        cls.adapter = _read(ADAPTER_IFACE)
        cls.comments = _read(COMMENTS_SYNC)
        cls.github = _read(GITHUB)
        cls.linear_graphql = _read(LINEAR_GRAPHQL)
        cls.linear_ladder = _read(LINEAR_LADDER)
        cls.linear_mcp = _read(LINEAR_MCP)
        cls.docs = _read(DOCS)

    # ---- R14: Phase-0 autonomy parity ----------------------------------

    def test_phase0_gate_recognizes_full_autonomy_marker_family(self) -> None:
        """The Phase-0 RALPH gate must recognize FLOW_AUTONOMOUS + mode:autonomous
        alongside the pre-existing FLOW_RALPH / REVIEW_RECEIPT_PATH."""
        for token in (
            "FLOW_RALPH",
            "REVIEW_RECEIPT_PATH",
            "FLOW_AUTONOMOUS",
            "mode:autonomous",
        ):
            with self.subTest(token=token):
                self.assertIn(
                    token,
                    self.steps,
                    f"Phase-0 gate must recognize {token!r} (R14 parity)",
                )

    def test_phase0_gate_folds_autonomy_into_the_ralph_flag(self) -> None:
        """The four signals must collapse into the single RALPH=1 assignment —
        the literal gate line carries all four (one shell condition)."""
        # The single gate condition sets RALPH and references all four markers.
        gate_window = self.steps.split("RALPH=0", 1)[1][:600]
        for token in (
            "FLOW_RALPH",
            "REVIEW_RECEIPT_PATH",
            "FLOW_AUTONOMOUS",
            "mode:autonomous",
        ):
            with self.subTest(token=token):
                self.assertIn(
                    token,
                    gate_window,
                    f"{token!r} must be in the single RALPH=1 gate condition",
                )

    def test_no_askuserquestion_under_autonomy_invariant_is_stated(self) -> None:
        """The hard invariant — under the marker NO path reaches AskUserQuestion —
        must be explicit, naming sync defer as the resolution."""
        self.assertIn("AskUserQuestion", self.steps)
        self.assertIn("sync defer", self.steps)
        # The invariant prose ties "never reachable under the marker" to R14.
        self.assertRegex(
            self.steps,
            r"(?s)AskUserQuestion is never reachable under the marker"
            r"|NO code path may reach .?AskUserQuestion",
            "R14 hard invariant (no prompt under the autonomy marker) must be stated",
        )

    def test_docs_document_the_parity_fix(self) -> None:
        """docs/tracker-sync.md must document the Phase-0 parity fix (R14)."""
        self.assertIn("FLOW_AUTONOMOUS", self.docs)
        self.assertIn("mode:autonomous", self.docs)
        self.assertIn("fn-68", self.docs)

    # ---- listOpenIssues: the 9th adapter method ------------------------

    def test_adapter_interface_declares_nine_methods(self) -> None:
        """The interface header must say NINE methods (was eight) and include
        listOpenIssues in the method table."""
        self.assertIn("Nine methods", self.adapter)
        self.assertNotIn("Eight methods", self.adapter)
        self.assertIn("listOpenIssues(filter)", self.adapter)

    def test_listopenissues_is_exact_match_no_ordering(self) -> None:
        """listOpenIssues must filter to the EXACT readyState lane — no
        'beyond'/ordering (the round-2 #4 / round-3 finding)."""
        self.assertIn("listOpenIssues", self.adapter)
        # exact-match language present
        self.assertRegex(
            self.adapter,
            r"(?i)exact",
            "listOpenIssues must be described as an exact-match filter",
        )
        # the "no ordering / no beyond" guard
        self.assertRegex(
            self.adapter,
            r"(?i)no state ordering|never inferred|no ordering",
            "listOpenIssues must rule out a 'beyond'/ordered lane (never inferred)",
        )

    def test_listopenissues_readystate_unset_is_noop_not_error(self) -> None:
        """readyState unset ⇒ documented noop returning [], never an error."""
        # In the adapter contract:
        self.assertRegex(
            self.adapter,
            r"(?s)readyState.{0,80}unset.{0,160}noop|noop.{0,160}readyState.{0,80}unset",
            "adapter-interface must state readyState-unset ⇒ noop, []",
        )
        # And in the steps.md list-open op:
        self.assertRegex(
            self.steps,
            r"(?s)tracker\.readyState is unset.{0,400}noop",
            "list-open must no-op with a note when readyState is unset",
        )

    def test_listopenissues_implemented_for_linear_and_github(self) -> None:
        """v1 implements listOpenIssues for BOTH Linear and GitHub."""
        # GitHub: gh issue list with the readyState label filter.
        self.assertIn("listOpenIssues", self.github)
        self.assertRegex(
            self.github,
            r"gh issue list[^\n]*--label",
            "GitHub listOpenIssues must filter by the readyState label",
        )
        self.assertRegex(
            self.github,
            r"--state open",
            "GitHub listOpenIssues must bound to open issues",
        )
        # Linear GraphQL: issues(filter:{state:{name:{eqIgnoreCase}}}).
        self.assertIn("listOpenIssues", self.linear_graphql)
        self.assertRegex(
            self.linear_graphql,
            r"eqIgnoreCase",
            "Linear listOpenIssues must match the state NAME exactly (eqIgnoreCase)",
        )
        # Linear ladder + MCP register it.
        self.assertIn("listOpenIssues", self.linear_ladder)
        self.assertIn("listOpenIssues", self.linear_mcp)

    # ---- Named skill ops: list-open / question -------------------------

    def test_named_ops_listed_in_phase0_operation_tokens(self) -> None:
        """list-open and question must be recognized operation tokens (Phase 0)."""
        self.assertIn("list-open", self.steps)
        self.assertIn("question", self.steps)
        # question takes a spec-id OR tracker-id.
        self.assertRegex(
            self.steps,
            r"question\s*<spec-id\s*\|\s*tracker-id>",
            "question op must accept <spec-id | tracker-id>",
        )

    def test_named_ops_are_skill_level_not_flowctl_transport(self) -> None:
        """The named ops must be explicitly skill-level + transport-blind, NOT
        flowctl transport (the architecture rule)."""
        self.assertRegex(
            self.steps,
            r"(?i)skill-level.{0,80}transport-blind|transport-blind.{0,80}NOT.{0,40}flowctl",
            "list-open/question must be stated skill-level + NOT flowctl transport",
        )

    # ---- R15: the question-valve anchor contract -----------------------

    def test_question_anchor_format(self) -> None:
        """The stable anchor must be the documented HTML-comment form with id +
        open|answered status."""
        self.assertIn("flow-next:question id=", self.steps)
        self.assertRegex(
            self.steps,
            r"flow-next:question id=<hash> status=open",
            "the question anchor must carry id=<hash> status=open",
        )
        self.assertIn("status=answered", self.steps)

    def test_question_id_hashes_stable_fields_only(self) -> None:
        """id hashes subjectId + blocked-stage + reasonCode + questionSlug;
        free prose is OUTSIDE the hash; subjectId is the spec id or opaque
        tracker id (NEVER a bare tracker key)."""
        for field in ("subjectId", "blockedStage", "reasonCode", "questionSlug"):
            with self.subTest(field=field):
                self.assertIn(
                    field,
                    self.steps,
                    f"the anchor id must hash {field!r}",
                )
        # subjectId = spec id when spec-backed else the opaque tracker id.
        self.assertRegex(
            self.steps,
            r"(?s)subjectId\s*=\s*the SPEC ID when spec-backed",
            "subjectId must be the spec id when spec-backed, else the tracker id",
        )
        # free prose OUTSIDE the hash.
        self.assertRegex(
            self.steps,
            r"(?i)free-prose reason.{0,60}OUTSIDE the hash"
            r"|prose.{0,40}OUTSIDE the hash",
            "the free prose must be OUTSIDE the hash (rephrasing must not duplicate)",
        )
        # NEVER a bare tracker key in the anchor.
        self.assertRegex(
            self.steps,
            r"(?i)NEVER a bare tracker (issue )?KEY|no bare tracker.{0,20}key",
            "the anchor must never render a bare tracker key (linkify hazard)",
        )

    def test_answer_marker_flat_tracker_fallback(self) -> None:
        """The flat-tracker (GitHub) answer is matched by the
        <!-- flow-next:answer id=<hash> --> marker, by id, threading-blind."""
        self.assertIn("flow-next:answer id=", self.steps)
        # GitHub adapter states comments are flat (parentId null) and the marker
        # is the load-bearing match.
        self.assertRegex(
            self.github,
            r"(?s)parentId.{0,40}null.{0,400}flow-next:answer"
            r"|flat.{0,400}flow-next:answer",
            "GitHub adapter must state the flat answer is matched by the id marker",
        )

    def test_comment_struct_gains_optional_parent_metadata(self) -> None:
        """The normalized comment struct gains optional reply/parent metadata
        (parentId) for threaded answer matching (Linear)."""
        self.assertIn("parentId", self.adapter)
        # Linear GraphQL pulls parent { id } into parentId.
        self.assertRegex(
            self.linear_graphql,
            r"parent\s*\{\s*id\s*\}",
            "Linear GraphQL listComments must select parent { id }",
        )
        self.assertIn("parentId", self.linear_graphql)

    def test_answer_imports_under_open_questions_and_flips_anchor(self) -> None:
        """A matched answer imports UNDER the matching ## Open Questions entry by
        id (not only ## Sync Log) and flips the anchor to answered."""
        self.assertIn("## Open Questions", self.steps)
        self.assertRegex(
            self.steps,
            r"(?s)import.{0,80}Open Questions|under the matching .?## Open Questions",
            "a matched answer must import under the matching ## Open Questions entry",
        )
        self.assertRegex(
            self.steps,
            r"(?s)flip.{0,40}answered|status=open .?> status=answered|→ status=answered",
            "the matched answer must flip the anchor to answered",
        )

    def test_tracker_only_question_exempt_from_specid_receipt(self) -> None:
        """A tracker-only question (no spec) is exempt from the spec-id sync
        receipt; its parked state lives in the tracker comments."""
        self.assertRegex(
            self.steps,
            r"(?s)tracker-only.{0,120}exempt from the spec-id"
            r"|exempt from the spec-id.{0,120}receipt",
            "tracker-only question must be exempt from the spec-id sync receipt",
        )
        self.assertRegex(
            self.steps,
            r"(?s)parked state lives in the tracker|parks in the tracker",
            "a tracker-only question's parked state must live in the tracker",
        )

    def test_comments_sync_documents_question_valve_markers(self) -> None:
        """comments-sync.md must document the question-valve marker family +
        its dedup-by-id, plus the flat-tracker round-trip fixture."""
        self.assertIn("flow-next:question id=", self.comments)
        self.assertIn("flow-next:answer", self.comments)
        # The flat-tracker round-trip fixture (Fixture C-G).
        self.assertRegex(
            self.comments,
            r"(?s)Fixture C-G.{0,400}flat",
            "comments-sync must carry a flat-tracker answer round-trip fixture",
        )
        # Idempotent-by-id fixture (Fixture C-F).
        self.assertIn("Fixture C-F", self.comments)

    def test_question_marker_is_flow_owned_not_sync_log(self) -> None:
        """A parked flow-next:question is flow-OWNED (marker set, NOT imported to
        the Sync Log). The adapter must detect it as part of a CLOSED marker
        vocabulary — detecting only flow-evt:<event> would import it wrongly."""
        # adapter-interface.md must define the closed marker vocabulary table and
        # map flow-next:question → a non-null marker.
        self.assertRegex(
            self.adapter,
            r"(?s)marker vocabulary|marker-vocabulary|Marker vocabulary",
            "adapter-interface must define the closed flow-owned marker vocabulary",
        )
        self.assertRegex(
            self.adapter,
            r"(?s)flow-next:question.{0,80}flow-evt:question",
            "flow-next:question must map to a non-null marker (flow-evt:question)",
        )
        # The 'not only flow-evt:<event>' caveat — the exact gap the review caught.
        self.assertRegex(
            self.adapter,
            r"(?i)not only .?flow-evt|NOT only .?flow-evt",
            "adapter must state marker detection is NOT only flow-evt:<event>",
        )
        # comments-sync states the question is flow-owned ⇒ not the Sync Log.
        self.assertRegex(
            self.comments,
            r"(?s)flow-next:question.{0,200}(NOT pulled into the\s*Sync Log|never the Sync Log)",
            "comments-sync must state a parked question is NOT imported to the Sync Log",
        )

    def test_answer_marker_is_human_content_claimed_by_id_first(self) -> None:
        """flow-next:answer is the ONE human-authored marker — marker stays null
        (genuine content), but the round-trip claims it by id BEFORE the generic
        Sync-Log append; an unmatched answer falls through to a real comment."""
        # adapter-interface: answer keeps marker null but surfaces its id.
        self.assertRegex(
            self.adapter,
            r"(?s)flow-next:answer.{0,400}(null|human)",
            "adapter must state flow-next:answer keeps marker null (human content)",
        )
        # comments-sync PULL flow claims the answer by id before Sync-Log append.
        self.assertRegex(
            self.comments,
            r"(?s)flow-next:answer.{0,200}(BEFORE|before).{0,80}Sync-?Log"
            r"|claim it by .?<id>.{0,120}BEFORE",
            "comments-sync PULL must claim the answer by id BEFORE the Sync-Log append",
        )
        # An unmatched answer is a genuine comment (falls through).
        self.assertRegex(
            self.comments,
            r"(?s)(no matching open question|matches no open question|unmatched).{0,160}"
            r"(Sync.?Log|genuine|real comment)",
            "an unmatched answer must fall through to a genuine Sync-Log comment",
        )

    def test_all_three_adapters_detect_the_closed_marker_set(self) -> None:
        """GitHub + Linear (GraphQL + MCP) listComments must each detect the
        closed flow-owned marker set (sync/question/status), not only flow-evt."""
        for name, text in (
            ("github", self.github),
            ("linear-graphql", self.linear_graphql),
            ("linear-mcp", self.linear_mcp),
        ):
            with self.subTest(adapter=name):
                self.assertIn(
                    "flow-next:question",
                    text,
                    f"{name} listComments must detect flow-next:question",
                )
                self.assertIn(
                    "flow-next:answer",
                    text,
                    f"{name} listComments must handle flow-next:answer (id surfaced)",
                )

    def test_no_stale_method_count_in_canonical_adapter_docs(self) -> None:
        """The interface is NINE methods now. No canonical adapter doc may still
        call the *interface* 'eight-method' / 'eight interface methods' OR
        'six-method' / 'six interface methods' (the review caught linear-ladder,
        then github/linear-graphql/linear-mcp). A bare 'six core methods' /
        'original six' reference to the original core subset is allowed — only the
        *interface-count* claims are forbidden."""
        forbidden = (
            "eight-method",
            "eight interface methods",
            "six-method",
            "six interface methods",
        )
        for name, text in (
            ("adapter-interface", self.adapter),
            ("linear-ladder", self.linear_ladder),
            ("linear-graphql", self.linear_graphql),
            ("linear-mcp", self.linear_mcp),
            ("github", self.github),
        ):
            lowered = text.lower()
            for phrase in forbidden:
                with self.subTest(doc=name, phrase=phrase):
                    self.assertNotIn(
                        phrase,
                        lowered,
                        f"{name} must not call the interface {phrase!r} (now nine; "
                        f"use 'nine-method' or 'original six core methods')",
                    )
        # The per-transport adapter docs must affirmatively say nine.
        for name, text in (
            ("linear-ladder", self.linear_ladder),
            ("github", self.github),
            ("linear-graphql", self.linear_graphql),
            ("linear-mcp", self.linear_mcp),
        ):
            with self.subTest(doc=name):
                self.assertRegex(
                    text,
                    r"(?i)nine-method|nine interface methods",
                    f"{name} must describe the interface as nine-method",
                )

    # ---- R16: reuse the existing readyState projection -----------------

    def test_r16_reuses_existing_readiness_projection_no_new_mechanism(self) -> None:
        """R16 reuses status-sync's readyState→ready projection — the steps.md
        must point at it as the existing mechanism, not introduce a new one."""
        # The status-sync readiness projection reference still exists.
        status_sync = SKILL_DIR / "references" / "status-sync.md"
        self.assertTrue(status_sync.exists())
        self.assertIn(
            "Readiness projection", _read(status_sync),
            "the existing status-sync readiness projection must remain the mechanism",
        )

    # ---- Codex mirror is fn-68.5's job, not this task ------------------

    def test_codex_mirror_exists_but_is_not_asserted_here(self) -> None:
        """The Codex mirror steps.md exists, but fn-68.2 deliberately does NOT
        regenerate it — that is fn-68.5. We assert only that the mirror file is
        present (so a missing mirror is caught), NOT that it carries fn-68
        content (asserting that would be wrong here)."""
        self.assertTrue(
            CODEX_STEPS.exists(),
            "the Codex mirror steps.md must exist (fn-68.5 regenerates its content)",
        )


if __name__ == "__main__":
    unittest.main()
