"""fn-147.1 — interview emits source tags, and cannot drift from capture's vocabulary.

`/flow-next:interview` writes acceptance criteria with the same trailing-token
provenance tags `/flow-next:capture` writes (`[user]` / `[paraphrase]` /
`[inferred]` / `[strategy:<track>]`). The vocabulary is deliberately REPEATED at
each emission site rather than centralised (fn-84.2 relocated capture's tables as
a "safe" DRY trim, regressed a fixture 15 -> 14, and was reverted — proximity is
accuracy-load-bearing). So "cannot drift" is enforced here, by asserting the
definitions match in both skill trees, not by DRYing the prose.

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is not asserted here.
"""

from __future__ import annotations

import pathlib
import re
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

CAPTURE_WORKFLOW = SKILLS / "flow-next-capture" / "workflow.md"
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
INTERVIEW_SKILL = SKILLS / "flow-next-interview" / "SKILL.md"
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-interview" / "references" / "write-back.md"
)
FIXTURE_DIR = pathlib.Path(__file__).parent / "fixtures" / "interview_source_tags"

TAGS = ("[user]", "[paraphrase]", "[inferred]", "[strategy:<track>]")

# The shared definitions. Byte-identical in capture and interview — if either
# side rewords one, this test fails and the drift is caught at the edit.
SHARED_DEFINITIONS = (
    "Verbatim from conversation evidence (exact quote or close paraphrase preserving meaning)",
    "User intent restated in spec language (semantic equivalence; no new constraints introduced)",
    "Agent fill-in (most-scrutinized; user must confirm at read-back)",
    "Derived from `STRATEGY.md` content",
)

# Invariants the interview guidance must carry at the emission sites.
WRITE_BACK_RULES = (
    "Tag only criteria this pass authors",
    "Never add, change, or remove a tag",
    "Untagged legacy criteria stay untagged",
    "never `[user]`",
    "Never ask about tagging",
    "Uniform tagging is a failure",
    "No self-blessing on unasked guesses",
)

# Emission sites that must each carry their own short tag imperative.
EMISSION_SITE_HEADINGS = (
    "### For NEW IDEA (text input, no Flow ID)",
    "### For EXISTING SPEC (fn-N that already has tasks)",
)


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


class InterviewSourceTagsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.capture_workflow = read(CAPTURE_WORKFLOW)
        cls.capture_phases = read(CAPTURE_PHASES)
        cls.interview_skill = read(INTERVIEW_SKILL)
        cls.write_back = read(INTERVIEW_WRITE_BACK)

    # --- R1: interview emits tags at all -------------------------------------

    def test_write_back_declares_full_vocabulary(self) -> None:
        for tag in TAGS:
            with self.subTest(tag=tag):
                self.assertIn(
                    tag,
                    self.write_back,
                    f"interview write-back.md never mentions {tag}",
                )

    def test_write_back_shows_trailing_token_format(self) -> None:
        self.assertRegex(
            self.write_back,
            r"- \*\*R\d+:\*\*.*\[inferred\]",
            "write-back.md must show the trailing-token bullet format by example",
        )
        self.assertIn("trailing source tag", self.write_back)

    def test_each_emission_site_repeats_the_imperative(self) -> None:
        """Proximity rule: every branch that writes criteria says so itself."""
        for heading in EMISSION_SITE_HEADINGS:
            with self.subTest(site=heading):
                self.assertIn(heading, self.write_back)
                start = self.write_back.index(heading) + len(heading)
                rest = self.write_back[start:]
                nxt = re.search(r"\n### ", rest)
                body = rest[: nxt.start()] if nxt else rest
                self.assertRegex(
                    body,
                    r"(?i)source-tag",
                    f"emission site {heading!r} carries no source-tag imperative",
                )

    def test_merged_body_contract_tags_new_criteria_only(self) -> None:
        self.assertIn(
            "newly appended R-IDs carry a trailing source tag",
            self.write_back,
        )
        self.assertIn("pre-existing bullets keep their tag", self.write_back)

    def test_skill_md_states_per_pass_user_semantics(self) -> None:
        """R7: a reader can tell what [user] means per pass."""
        self.assertIn("the PO answering in this pass", self.interview_skill)
        self.assertIn("the tech lead answering in this pass", self.interview_skill)
        self.assertIn(
            "the PO under `--scope=business`, the tech lead under `--scope=technical`",
            self.write_back,
        )

    # --- R2: provenance is frozen -------------------------------------------

    def test_write_back_carries_the_hard_rules(self) -> None:
        for rule in WRITE_BACK_RULES:
            with self.subTest(rule=rule):
                self.assertIn(
                    rule,
                    self.write_back,
                    f"interview write-back.md missing tag invariant: {rule!r}",
                )

    # --- R3: drift pin ------------------------------------------------------

    def test_tag_definitions_match_capture(self) -> None:
        """Neither skill can reword a definition alone."""
        sources = {
            "capture/workflow.md": self.capture_workflow,
            "capture/phases.md": self.capture_phases,
            "interview/references/write-back.md": self.write_back,
        }
        for definition in SHARED_DEFINITIONS:
            for label, text in sources.items():
                with self.subTest(definition=definition, file=label):
                    self.assertIn(
                        definition,
                        text,
                        f"{label} no longer carries the shared definition "
                        f"{definition!r} — capture and interview have drifted",
                    )

    # --- R5: tags discriminate on the frozen fixture ------------------------

    def test_frozen_fixture_shows_mixed_tags(self) -> None:
        emitted = read(FIXTURE_DIR / "emitted-criteria.md")
        found = re.findall(
            r"^- \*\*R\d+:\*\* .*?(\[[a-z]+(?::[^\]]+)?\])\s*$",
            emitted,
            flags=re.MULTILINE,
        )
        self.assertGreaterEqual(len(found), 4, "fixture emission is too small to judge")
        distinct = set(found)
        self.assertGreaterEqual(
            len(distinct),
            3,
            f"fixture emission does not discriminate — tags collapsed to {distinct}",
        )
        self.assertIn("[inferred]", distinct)
        self.assertTrue(
            {"[user]", "[paraphrase]"} & distinct,
            "fixture emission has no answer-grounded criterion",
        )

    def test_frozen_fixture_transcript_present(self) -> None:
        transcript = read(FIXTURE_DIR / "transcript.md")
        self.assertIn("Frozen", transcript)
        self.assertIn("Not asked at all", transcript)


if __name__ == "__main__":
    unittest.main()
