"""fn-147.1 — interview emits source tags, and cannot drift from capture's vocabulary.

`/flow-next:refine` writes acceptance criteria with the same trailing-token
provenance tags `/flow-next:capture` writes (`[user]` / `[paraphrase]` /
`[inferred]` / `[strategy:<track>]`). The vocabulary is deliberately REPEATED at
each emission site rather than centralised (fn-84.2 relocated capture's tables as
a "safe" DRY trim, regressed a fixture 15 -> 14, and was reverted — proximity is
accuracy-load-bearing). So "cannot drift" is enforced here structurally: the
same tag vocabulary in both tables, each side's `[user]` decision token, the
shared tally shape, and the routes between the files. Definition sentences are
not pinned (G2, fn-256 R9).

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is not asserted here.
"""

from __future__ import annotations

import pathlib
import re
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

CAPTURE_WORKFLOW = SKILLS / "flow-next-capture" / "workflow.md"
# Branch-disclosure (fn-169) left capture's source-tag taxonomy as a SINGLE
# copy in phases.md; workflow.md §2.3 now cross-links it instead of carrying a
# second table. Capture-side vocabulary pins therefore target phases.md, and
# workflow.md is pinned to still route there.
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
CAPTURE_TAXONOMY_LINK = "[phases.md](phases.md) §Source-tag taxonomy"
INTERVIEW_SKILL = SKILLS / "flow-next-refine" / "SKILL.md"
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-refine" / "references" / "write-back.md"
)
FIXTURE_DIR = pathlib.Path(__file__).parent / "fixtures" / "interview_source_tags"

TAGS = ("[user]", "[paraphrase]", "[inferred]", "[strategy:<track>]")

# `[user]` decision tokens: capture's row must anchor to the evidence block and
# must not carry the retired hole; interview's row must keep its deliberate
# close-paraphrase semantics (it has no evidence block to anchor findability).
CAPTURE_USER_TOKEN = "Conversation Evidence"
CAPTURE_USER_HOLE = "close paraphrase"
INTERVIEW_USER_TOKEN = "close paraphrase"


def _user_row(doc: str, label: str) -> str:
    """The `[user]` source-tag table row of a skill doc."""
    for line in doc.splitlines():
        if line.lstrip().startswith("| `[user]` |"):
            return line
    raise AssertionError(f"{label} has no `[user]` source-tag table row")


# Emission sites that must each carry their own short tag imperative.
EMISSION_SITE_HEADINGS = (
    "### For NEW IDEA (text input, no Flow ID)",
    "### For EXISTING SPEC (fn-N that already has tasks)",
)


# The shared read-back tally artifact. Capture emits this shape; interview must
# emit the same one. Pinned so the `·` separator cannot regress to `/`.
TALLY_TEMPLATE = "Source: [user] N · [paraphrase] M · [strategy] K · [inferred] L"

# Header of the source-tag table in every source file. Extraction is anchored to
# it so a sibling table (capture/phases.md's confidence markers) cannot leak in.
_TAG_TABLE_HEADER = re.compile(r"^\|\s*Tag\s*\|\s*Meaning\s*\|", re.MULTILINE)
_TAG_ROW = re.compile(r"^\|\s*`(\[[^\]`]+\])`\s*\|")


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def tag_table_tokens(text: str) -> set[str]:
    """Tag tokens from the source-tag table only.

    Anchors on the `| Tag | Meaning |` header, skips the `|---|` rule, then
    consumes contiguous table rows until the table ends. Returns a set so the
    caller can assert equality (catching additions, not just absences).
    """
    m = _TAG_TABLE_HEADER.search(text)
    if not m:
        return set()
    tokens: set[str] = set()
    for line in text[m.end() :].split("\n")[1:]:  # [1:] skips the |---| rule
        if not line.startswith("|"):
            break
        row = _TAG_ROW.match(line)
        if row:
            tokens.add(row.group(1))
    return tokens


class InterviewSourceTagsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.capture_workflow = read(CAPTURE_WORKFLOW)
        cls.capture_phases = read(CAPTURE_PHASES)
        cls.interview_skill = read(INTERVIEW_SKILL)
        cls.write_back = read(INTERVIEW_WRITE_BACK)

    # --- R1: interview emits tags at all -------------------------------------

    def test_write_back_declares_full_vocabulary(self) -> None:
        for tag in TAGS:
            with self.subTest(tag=tag):
                self.assertIn(
                    tag,
                    self.write_back,
                    f"interview write-back.md never mentions {tag}",
                )

    def test_write_back_shows_trailing_token_format(self) -> None:
        self.assertRegex(
            self.write_back,
            r"- \*\*R\d+:\*\*.*\[inferred\]",
            "write-back.md must show the trailing-token bullet format by example",
        )

    def test_each_emission_site_repeats_the_imperative(self) -> None:
        """Proximity rule: every branch that writes criteria says so itself."""
        for heading in EMISSION_SITE_HEADINGS:
            with self.subTest(site=heading):
                self.assertIn(heading, self.write_back)
                start = self.write_back.index(heading) + len(heading)
                rest = self.write_back[start:]
                nxt = re.search(r"\n### ", rest)
                body = rest[: nxt.start()] if nxt else rest
                self.assertRegex(
                    body,
                    r"(?i)source-tag",
                    f"emission site {heading!r} carries no source-tag imperative",
                )

    def test_skill_md_routes_to_both_pass_references(self) -> None:
        """R7: each pass states its own `[user]` identity in its own reference,
        so SKILL.md must keep the routes to both (reachability)."""
        for link in (
            "[`references/pass-business.md`](references/pass-business.md)",
            "[`references/pass-technical.md`](references/pass-technical.md)",
        ):
            with self.subTest(link=link):
                self.assertIn(link, self.interview_skill)

    # --- R3: drift pin ------------------------------------------------------

    def test_user_rows_keep_their_decision_tokens(self) -> None:
        """`[user]` is per-side: capture findability vs interview pass-identity.

        Any rewording that preserves the decision passes.
        """
        # Reachability: capture's spine must still route to the single copy.
        self.assertIn(CAPTURE_TAXONOMY_LINK, self.capture_workflow)
        capture_row = _user_row(self.capture_phases, "capture/phases.md")
        interview_row = _user_row(self.write_back, "interview write-back.md")
        self.assertIn(
            CAPTURE_USER_TOKEN,
            capture_row,
            "capture's [user] row lost its evidence-block anchor — "
            "findability is the decision, wording is free",
        )
        self.assertNotIn(
            CAPTURE_USER_HOLE,
            capture_row,
            "the retired 'close paraphrase' wording returned to capture's "
            "[user] row — restatements belong to [paraphrase]",
        )
        self.assertIn(
            INTERVIEW_USER_TOKEN,
            interview_row,
            "interview's [user] row lost its deliberate pass-identity "
            "semantics (no evidence block anchors findability there)",
        )

    def test_tag_vocabulary_matches_capture(self) -> None:
        """Neither skill can rename, drop, OR ADD a tag token alone.

        Set-EQUALITY, not presence: a presence-only assertion structurally
        cannot catch an ADDITION (a fifth tag on one side leaves every existing
        assertion green). Extraction is scoped to each file's source-tag table
        because `capture/phases.md` carries a SECOND table of confidence
        markers (`[high]` / `[judgment-call]` / `[your-call]`) that would
        otherwise contaminate the set.
        """
        sources = {
            "capture/phases.md": self.capture_phases,
            "interview/references/write-back.md": self.write_back,
        }
        # Reachability: capture's spine must still route to the single copy.
        self.assertIn(CAPTURE_TAXONOMY_LINK, self.capture_workflow)
        for label, text in sources.items():
            with self.subTest(file=label):
                found = tag_table_tokens(text)
                self.assertEqual(
                    found,
                    set(TAGS),
                    f"{label} source-tag table is {sorted(found)}, expected "
                    f"{sorted(TAGS)} — the shared vocabulary has drifted "
                    f"(a renamed, dropped, or ADDED tag all land here)",
                )

    def test_tally_template_matches_capture(self) -> None:
        """Freezes the m3 fix: the tally shape must stay byte-identical.

        Interview's read-back tally is the same artifact capture emits, so the
        separator must not regress to `/` on one side. Capture is the incumbent
        (its files are not editable here per fn-84.2), so both sides are pinned
        to capture's middot form.
        """
        self.assertIn("[docs/read-back.md](../../docs/read-back.md)", self.capture_workflow)
        for label, text in (
            ("docs/read-back.md", read(PLUGIN / "docs" / "read-back.md")),
            ("interview/references/write-back.md", self.write_back),
        ):
            with self.subTest(file=label):
                self.assertIn(
                    TALLY_TEMPLATE,
                    text,
                    f"{label} no longer carries the shared tally shape "
                    f"{TALLY_TEMPLATE!r} — separator or field order drifted",
                )

    # --- R5: tags discriminate on the frozen fixture ------------------------

    def test_frozen_fixture_shows_mixed_tags(self) -> None:
        emitted = read(FIXTURE_DIR / "emitted-criteria.md")
        found = re.findall(
            r"^- \*\*R\d+:\*\* .*?(\[[a-z]+(?::[^\]]+)?\])\s*$",
            emitted,
            flags=re.MULTILINE,
        )
        self.assertGreaterEqual(len(found), 4, "fixture emission is too small to judge")
        distinct = set(found)
        self.assertGreaterEqual(
            len(distinct),
            3,
            f"fixture emission does not discriminate — tags collapsed to {distinct}",
        )
        self.assertIn("[inferred]", distinct)
        self.assertTrue(
            {"[user]", "[paraphrase]"} & distinct,
            "fixture emission has no answer-grounded criterion",
        )

    def test_frozen_fixture_transcript_present(self) -> None:
        transcript = read(FIXTURE_DIR / "transcript.md")
        self.assertIn("Frozen", transcript)
        self.assertIn("Not asked at all", transcript)


if __name__ == "__main__":
    unittest.main()
