"""fn-147.1 — interview emits source tags, and cannot drift from capture's vocabulary.

`/flow-next:interview` writes acceptance criteria with the same trailing-token
provenance tags `/flow-next:capture` writes (`[user]` / `[paraphrase]` /
`[inferred]` / `[strategy:<track>]`). The vocabulary is deliberately REPEATED at
each emission site rather than centralised (fn-84.2 relocated capture's tables as
a "safe" DRY trim, regressed a fixture 15 -> 14, and was reverted — proximity is
accuracy-load-bearing). So "cannot drift" is enforced here, by asserting the
definitions match in both skill trees, not by DRYing the prose.

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is not asserted here.
"""

from __future__ import annotations

import pathlib
import re
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

CAPTURE_WORKFLOW = SKILLS / "flow-next-capture" / "workflow.md"
# Branch-disclosure (fn-169) left capture's source-tag taxonomy as a SINGLE
# copy in phases.md; workflow.md §2.3 now cross-links it instead of carrying a
# second table. Capture-side vocabulary/definition pins therefore target
# phases.md, and workflow.md is pinned to still route there.
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
CAPTURE_TAXONOMY_LINK = "[phases.md](phases.md) §Source-tag taxonomy"
INTERVIEW_SKILL = SKILLS / "flow-next-interview" / "SKILL.md"
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-interview" / "references" / "write-back.md"
)
# The per-pass `[user]` semantics moved to the scope references the SKILL.md
# scope switch loads.
INTERVIEW_PASS_BUSINESS = (
    SKILLS / "flow-next-interview" / "references" / "pass-business.md"
)
INTERVIEW_PASS_TECHNICAL = (
    SKILLS / "flow-next-interview" / "references" / "pass-technical.md"
)
FIXTURE_DIR = pathlib.Path(__file__).parent / "fixtures" / "interview_source_tags"

TAGS = ("[user]", "[paraphrase]", "[inferred]", "[strategy:<track>]")

# The shared definitions. Byte-identical in capture and interview — if either
# side rewords one, this test fails and the drift is caught at the edit.
#
# `[strategy:<track>]` is pinned by PREFIX only here because capture's own two
# copies legitimately differ past it: workflow.md carries the long form
# ("...H3 sub-block); track name lives literally in the tag") while phases.md
# carries a shorter one ("...quote of approach / track body"). The prefix is the
# most both can share. The long form is pinned separately, for the
# workflow.md <-> write-back.md pair only, by STRATEGY_LONG_FORM below.
SHARED_DEFINITIONS = (
    "Verbatim from conversation evidence (exact quote or close paraphrase preserving meaning)",
    "User intent restated in spec language (semantic equivalence; no new constraints introduced)",
    "Agent fill-in (most-scrutinized; user must confirm at read-back)",
    "Derived from `STRATEGY.md` content",
)

# Interview copied capture/workflow.md's long `[strategy]` form verbatim. Pin the
# whole tail so the substantive part cannot drift alone (the SHARED_DEFINITIONS
# prefix above would not notice). phases.md is deliberately excluded — its
# wording is its own.
STRATEGY_LONG_FORM = (
    "Derived from `STRATEGY.md` content (verbatim or near-verbatim from "
    "`approach` or a `### <track-name>` H3 sub-block); track name lives "
    "literally in the tag"
)

# Invariants the interview guidance must carry at the emission sites.
WRITE_BACK_RULES = (
    "Tag only criteria this pass authors",
    "Never add, change, or remove a tag",
    "Untagged legacy criteria stay untagged",
    "never `[user]`",
    "Never ask about tagging",
    "Uniform tagging is a failure",
    "No self-blessing on unasked guesses",
)

# Emission sites that must each carry their own short tag imperative.
EMISSION_SITE_HEADINGS = (
    "### For NEW IDEA (text input, no Flow ID)",
    "### For EXISTING SPEC (fn-N that already has tasks)",
)


# The shared read-back tally artifact. Capture emits this shape; interview must
# emit the same one. Pinned so the `·` separator cannot regress to `/`.
TALLY_TEMPLATE = "Source: [user] N · [paraphrase] M · [strategy] K · [inferred] L"

# Header of the source-tag table in every source file. Extraction is anchored to
# it so a sibling table (capture/phases.md's confidence markers) cannot leak in.
_TAG_TABLE_HEADER = re.compile(r"^\|\s*Tag\s*\|\s*Meaning\s*\|", re.MULTILINE)
_TAG_ROW = re.compile(r"^\|\s*`(\[[^\]`]+\])`\s*\|")


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def tag_table_tokens(text: str) -> set[str]:
    """Tag tokens from the source-tag table only.

    Anchors on the `| Tag | Meaning |` header, skips the `|---|` rule, then
    consumes contiguous table rows until the table ends. Returns a set so the
    caller can assert equality (catching additions, not just absences).
    """
    m = _TAG_TABLE_HEADER.search(text)
    if not m:
        return set()
    tokens: set[str] = set()
    for line in text[m.end() :].split("\n")[1:]:  # [1:] skips the |---| rule
        if not line.startswith("|"):
            break
        row = _TAG_ROW.match(line)
        if row:
            tokens.add(row.group(1))
    return tokens


class InterviewSourceTagsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.capture_workflow = read(CAPTURE_WORKFLOW)
        cls.capture_phases = read(CAPTURE_PHASES)
        cls.interview_skill = read(INTERVIEW_SKILL)
        cls.write_back = read(INTERVIEW_WRITE_BACK)
        cls.pass_business = read(INTERVIEW_PASS_BUSINESS)
        cls.pass_technical = read(INTERVIEW_PASS_TECHNICAL)

    # --- R1: interview emits tags at all -------------------------------------

    def test_write_back_declares_full_vocabulary(self) -> None:
        for tag in TAGS:
            with self.subTest(tag=tag):
                self.assertIn(
                    tag,
                    self.write_back,
                    f"interview write-back.md never mentions {tag}",
                )

    def test_write_back_shows_trailing_token_format(self) -> None:
        self.assertRegex(
            self.write_back,
            r"- \*\*R\d+:\*\*.*\[inferred\]",
            "write-back.md must show the trailing-token bullet format by example",
        )
        self.assertIn("trailing source tag", self.write_back)

    def test_each_emission_site_repeats_the_imperative(self) -> None:
        """Proximity rule: every branch that writes criteria says so itself."""
        for heading in EMISSION_SITE_HEADINGS:
            with self.subTest(site=heading):
                self.assertIn(heading, self.write_back)
                start = self.write_back.index(heading) + len(heading)
                rest = self.write_back[start:]
                nxt = re.search(r"\n### ", rest)
                body = rest[: nxt.start()] if nxt else rest
                self.assertRegex(
                    body,
                    r"(?i)source-tag",
                    f"emission site {heading!r} carries no source-tag imperative",
                )

    def test_merged_body_contract_tags_new_criteria_only(self) -> None:
        self.assertIn(
            "newly appended R-IDs carry a trailing source tag",
            self.write_back,
        )
        self.assertIn("pre-existing bullets keep their tag", self.write_back)

    def test_skill_md_states_per_pass_user_semantics(self) -> None:
        """R7: a reader can tell what [user] means per pass.

        Branch-disclosure moved the per-pass merge contracts into the scope
        references SKILL.md's scope switch loads, so each pass now states its
        own `[user]` identity in its own file. SKILL.md keeps the pass-neutral
        rule plus the routes to both references (reachability).
        """
        self.assertIn("the PO answering in this pass", self.pass_business)
        self.assertIn(
            "the tech lead answering in this pass", self.pass_technical
        )
        self.assertIn(
            "`[user]` = the human answering in this pass", self.interview_skill
        )
        for link in (
            "[`references/pass-business.md`](references/pass-business.md)",
            "[`references/pass-technical.md`](references/pass-technical.md)",
        ):
            self.assertIn(link, self.interview_skill)
        self.assertIn(
            "the PO under `--scope=business`, the tech lead under `--scope=technical`",
            self.write_back,
        )

    # --- R2: provenance is frozen -------------------------------------------

    def test_write_back_carries_the_hard_rules(self) -> None:
        for rule in WRITE_BACK_RULES:
            with self.subTest(rule=rule):
                self.assertIn(
                    rule,
                    self.write_back,
                    f"interview write-back.md missing tag invariant: {rule!r}",
                )

    # --- R3: drift pin ------------------------------------------------------

    def test_tag_definitions_match_capture(self) -> None:
        """Neither skill can reword a definition alone."""
        sources = {
            "capture/phases.md": self.capture_phases,
            "interview/references/write-back.md": self.write_back,
        }
        # Reachability: capture's spine must still route to the single copy.
        self.assertIn(CAPTURE_TAXONOMY_LINK, self.capture_workflow)
        for definition in SHARED_DEFINITIONS:
            for label, text in sources.items():
                with self.subTest(definition=definition, file=label):
                    self.assertIn(
                        definition,
                        text,
                        f"{label} no longer carries the shared definition "
                        f"{definition!r} — capture and interview have drifted",
                    )

    def test_tag_vocabulary_matches_capture(self) -> None:
        """Neither skill can rename, drop, OR ADD a tag token alone.

        Without this, the definitions pin above passes while capture renames
        `[user]` -> `[stated]` and interview silently diverges: the
        Meaning-column sentences carry no tag tokens, so they cannot detect a
        rename.

        Set-EQUALITY, not presence: a presence-only assertion structurally
        cannot catch an ADDITION (a fifth tag on one side leaves every existing
        assertion green). Extraction is scoped to each file's source-tag table
        because `capture/phases.md` carries a SECOND table of confidence
        markers (`[high]` / `[judgment-call]` / `[your-call]`) that would
        otherwise contaminate the set.
        """
        sources = {
            "capture/phases.md": self.capture_phases,
            "interview/references/write-back.md": self.write_back,
        }
        # Reachability: capture's spine must still route to the single copy.
        self.assertIn(CAPTURE_TAXONOMY_LINK, self.capture_workflow)
        for label, text in sources.items():
            with self.subTest(file=label):
                found = tag_table_tokens(text)
                self.assertEqual(
                    found,
                    set(TAGS),
                    f"{label} source-tag table is {sorted(found)}, expected "
                    f"{sorted(TAGS)} — the shared vocabulary has drifted "
                    f"(a renamed, dropped, or ADDED tag all land here)",
                )

    def test_tally_template_matches_capture(self) -> None:
        """Freezes the m3 fix: the tally shape must stay byte-identical.

        Interview's read-back tally is the same artifact capture emits, so the
        separator must not regress to `/` on one side. Capture is the incumbent
        (its files are not editable here per fn-84.2), so both sides are pinned
        to capture's middot form.
        """
        for label, text in (
            ("capture/workflow.md", self.capture_workflow),
            ("interview/references/write-back.md", self.write_back),
        ):
            with self.subTest(file=label):
                self.assertIn(
                    TALLY_TEMPLATE,
                    text,
                    f"{label} no longer carries the shared tally shape "
                    f"{TALLY_TEMPLATE!r} — separator or field order drifted",
                )

    def test_strategy_long_form_matches_capture_workflow(self) -> None:
        """The `[strategy]` tail interview copied cannot drift alone.

        SHARED_DEFINITIONS pins only the prefix, so without this the
        substantive tail could change on one side unnoticed.

        Branch-disclosure deduped capture's second tag table out of
        workflow.md; the capture-side long form now lives once in phases.md
        §Source-tag taxonomy (same substance, capture's own sentence shape), so
        the tail is pinned per-side: byte-exact on interview's copy, and by its
        two load-bearing clauses on capture's surviving copy.
        """
        self.assertIn(
            STRATEGY_LONG_FORM,
            self.write_back,
            "interview/references/write-back.md no longer carries the full "
            "`[strategy]` definition — the pair has drifted",
        )
        for clause in (
            "`### <track-name>` H3 sub-block",
            "track name lives literally in the tag",
        ):
            with self.subTest(clause=clause):
                self.assertIn(
                    clause,
                    self.capture_phases,
                    f"capture/phases.md no longer carries the `[strategy]` "
                    f"tail clause {clause!r} — the pair has drifted",
                )
        # Reachability: capture's spine routes to that single copy.
        self.assertIn(CAPTURE_TAXONOMY_LINK, self.capture_workflow)

    # --- R5: tags discriminate on the frozen fixture ------------------------

    def test_frozen_fixture_shows_mixed_tags(self) -> None:
        emitted = read(FIXTURE_DIR / "emitted-criteria.md")
        found = re.findall(
            r"^- \*\*R\d+:\*\* .*?(\[[a-z]+(?::[^\]]+)?\])\s*$",
            emitted,
            flags=re.MULTILINE,
        )
        self.assertGreaterEqual(len(found), 4, "fixture emission is too small to judge")
        distinct = set(found)
        self.assertGreaterEqual(
            len(distinct),
            3,
            f"fixture emission does not discriminate — tags collapsed to {distinct}",
        )
        self.assertIn("[inferred]", distinct)
        self.assertTrue(
            {"[user]", "[paraphrase]"} & distinct,
            "fixture emission has no answer-grounded criterion",
        )

    def test_frozen_fixture_transcript_present(self) -> None:
        transcript = read(FIXTURE_DIR / "transcript.md")
        self.assertIn("Frozen", transcript)
        self.assertIn("Not asked at all", transcript)


if __name__ == "__main__":
    unittest.main()
