"""fn-123.5 / R13 — print-then-ask read-back contract (canonical prose only).

Skills that show a draft/diff for approval must print the FULL markdown as an
ordinary assistant message FIRST, then issue a SHORT AskUserQuestion (one-line
pointer + [inferred] tally/warnings + options only). Multi-paragraph drafts,
diffs, and criteria lists must never live in ask bodies — they render as
collapsed plain text on every host.

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is intentionally not asserted here (this worktree task does
not regenerate the mirror).
"""

from __future__ import annotations

import pathlib
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

CAPTURE_SKILL = SKILLS / "flow-next-capture" / "SKILL.md"
CAPTURE_WORKFLOW = SKILLS / "flow-next-capture" / "workflow.md"
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
INTERVIEW_DOC_AWARE = (
    SKILLS / "flow-next-interview" / "references" / "doc-aware.md"
)
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-interview" / "references" / "write-back.md"
)

# New contract — must appear in the files that own the approval surface.
PRINT_THEN_ASK_TOKENS = (
    "print-then-ask",
    "ordinary",  # ordinary assistant message / ordinary markdown
)

# Capture Phase 4 surfaces (workflow is the authoritative procedure).
CAPTURE_WORKFLOW_REQUIRED = (
    "print-then-ask",
    "ordinary assistant",
    "one-line pointer",
    "Never embed multi-paragraph",
    "reprint",  # edit cycles reprint revised draft
)

# Capture SKILL.md overview must name the contract (not re-embed long ask body).
CAPTURE_SKILL_REQUIRED = (
    "print-then-ask",
    "ordinary markdown",
    "never embed multi-paragraph",
)

# Capture phases decision tree / phase table.
CAPTURE_PHASES_REQUIRED = (
    "print-then-ask",
    "reprint",
)

# Interview decision-entry + write-back approvals.
INTERVIEW_DOC_AWARE_REQUIRED = (
    "Print-then-ask",
    "ordinary assistant",
    "SHORT",
)

INTERVIEW_WRITE_BACK_REQUIRED = (
    "Print-then-ask",
    "ordinary assistant",
    "one-line pointer",
)

# Old embed-in-body wording that made long drafts unreadable — must be gone.
FORBIDDEN_EMBED_PHRASES = (
    # Capture Phase 4 old ask body that listed every criterion inside the question.
    "Full draft in the Write render above (expand if collapsed)",
    "Every acceptance criterion's substance, one short plain line each",
    "the user must see what they are approving inside the question",
    # Interview decision-entry old allowance (explicit R13 target).
    "inline in the question or in the message preceding",
    "Show the full body inline in the question",
    # Old capture overview that put the summary payload / criteria in the ask.
    "the `AskUserQuestion` body carries the plain-language summary payload",
    "every criterion in one plain line",
)


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


class ReadbackAskContract(unittest.TestCase):
    """Print-then-ask present; old long-question embed wording absent."""

    def setUp(self) -> None:
        for path in (
            CAPTURE_SKILL,
            CAPTURE_WORKFLOW,
            CAPTURE_PHASES,
            INTERVIEW_DOC_AWARE,
            INTERVIEW_WRITE_BACK,
        ):
            self.assertTrue(path.is_file(), f"missing canonical file: {path}")

        self.capture_skill = _read(CAPTURE_SKILL)
        self.capture_workflow = _read(CAPTURE_WORKFLOW)
        self.capture_phases = _read(CAPTURE_PHASES)
        self.doc_aware = _read(INTERVIEW_DOC_AWARE)
        self.write_back = _read(INTERVIEW_WRITE_BACK)
        self.combined = "\n".join(
            (
                self.capture_skill,
                self.capture_workflow,
                self.capture_phases,
                self.doc_aware,
                self.write_back,
            )
        )

    def _assert_tokens(self, text: str, tokens: tuple[str, ...], label: str) -> None:
        for token in tokens:
            with self.subTest(file=label, token=token):
                self.assertIn(
                    token,
                    text,
                    f"{label} missing required print-then-ask token: {token!r}",
                )

    def test_capture_workflow_print_then_ask(self) -> None:
        self._assert_tokens(
            self.capture_workflow, CAPTURE_WORKFLOW_REQUIRED, "capture/workflow.md"
        )
        # Rewrite-mode diff is printed as ordinary markdown, not only in the ask.
        self.assertIn("rewrite", self.capture_workflow.lower())
        self.assertIn(
            "diff",
            self.capture_workflow.lower(),
        )
        # Short ask shape: pointer + tally + options.
        self.assertIn("[inferred]", self.capture_workflow)
        self.assertIn("options", self.capture_workflow.lower())

    def test_capture_skill_print_then_ask(self) -> None:
        self._assert_tokens(
            self.capture_skill, CAPTURE_SKILL_REQUIRED, "capture/SKILL.md"
        )

    def test_capture_phases_print_then_ask(self) -> None:
        self._assert_tokens(
            self.capture_phases, CAPTURE_PHASES_REQUIRED, "capture/phases.md"
        )

    def test_interview_decision_entry_print_then_ask(self) -> None:
        self._assert_tokens(
            self.doc_aware,
            INTERVIEW_DOC_AWARE_REQUIRED,
            "interview/references/doc-aware.md",
        )
        # Explicit print-first of the full draft (not ask-body embed).
        self.assertIn("FULL decision-entry draft", self.doc_aware)
        self.assertIn("reprint the full revised draft", self.doc_aware)
        # Old allowance must not reappear as a positive instruction.
        self.assertNotIn(
            "inline in the question or in the message preceding",
            self.doc_aware,
        )

    def test_interview_write_back_print_then_ask(self) -> None:
        self._assert_tokens(
            self.write_back,
            INTERVIEW_WRITE_BACK_REQUIRED,
            "interview/references/write-back.md",
        )
        self.assertIn("reprint the full revised draft", self.write_back)

    def test_old_embed_in_body_wording_absent(self) -> None:
        for phrase in FORBIDDEN_EMBED_PHRASES:
            with self.subTest(phrase=phrase):
                self.assertNotIn(
                    phrase,
                    self.combined,
                    f"old embed-in-ask-body wording still present: {phrase!r}",
                )

    def test_autofix_path_still_non_interactive(self) -> None:
        """Autofix remains non-interactive; --yes is still the consent substitute."""
        # Capture SKILL + workflow keep autofix without AskUserQuestion.
        self.assertIn("mode:autofix", self.capture_skill)
        self.assertIn("--yes", self.capture_skill)
        self.assertIn("No user questions", self.capture_skill)
        # Autofix branch still documents --yes as read-back substitute.
        self.assertRegex(
            self.capture_workflow,
            r"(?i)autofix.*--yes|`--yes`.*substitut",
        )


if __name__ == "__main__":
    unittest.main()


class TestPrintThenAskOrdering(unittest.TestCase):
    """fn-123 review hardening: assert ORDER and ask-brevity, not just tokens.

    The §4.1 contract is a numbered sequence: print the full draft FIRST
    (item 1), then the short ask (item 2). Token presence alone would pass a
    regressed skill that re-embedded the draft in the ask while keeping the
    prose; these tests slice the owning section and check order + forbidden
    embed wording.
    """

    def setUp(self) -> None:
        self.workflow = _read(CAPTURE_WORKFLOW)

    def _contract_block(self) -> str:
        start = self.workflow.find("Print-then-ask contract")
        self.assertGreater(start, -1, "capture workflow lost the print-then-ask contract block")
        return self.workflow[start : start + 2500]

    def test_print_precedes_ask_in_contract_block(self) -> None:
        block = self._contract_block()
        print_pos = block.find("Print the FULL draft markdown as an ordinary assistant message FIRST")
        ask_pos = block.find("issue a **short** `AskUserQuestion`")
        self.assertGreater(print_pos, -1, "contract lost the print-first step")
        self.assertGreater(ask_pos, -1, "contract lost the short-ask step")
        self.assertLess(print_pos, ask_pos, "print step must precede the ask step")

    def test_ask_body_forbids_embedded_drafts(self) -> None:
        block = self._contract_block()
        self.assertIn(
            "Never embed multi-paragraph drafts, diffs, or criteria lists in the ask body",
            block,
        )

    def test_old_embed_wording_absent_everywhere(self) -> None:
        for path in (CAPTURE_SKILL, CAPTURE_WORKFLOW, CAPTURE_PHASES, INTERVIEW_DOC_AWARE, INTERVIEW_WRITE_BACK):
            text = _read(path)
            for forbidden in (
                "inline in the question or in the message preceding it",
                "the question body must say the full draft is in the Write render above",
                "rides in the §4.2 question body",
            ):
                self.assertNotIn(forbidden, text, f"{path.name}: regressed to old embed-in-ask wording: {forbidden!r}")

    def test_edit_cycle_reprints_before_reask(self) -> None:
        combined = "\n".join(_read(p) for p in (CAPTURE_SKILL, CAPTURE_WORKFLOW, INTERVIEW_DOC_AWARE, INTERVIEW_WRITE_BACK))
        self.assertIn("reprint", combined.lower())
