"""fn-123.5 / R13 — print-then-ask read-back contract (canonical prose only).

Skills that show a draft/diff for approval must print the FULL markdown as an
ordinary assistant message FIRST, then issue a SHORT AskUserQuestion. This
file keeps the contract tokens, the ordering (print before ask), and the
negative guards against the old embed-drafts-in-ask-bodies wording.

Prose-quality pins removed 2026-08-07 - judged via .flow/criteria.md G1, not grep.

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is intentionally not asserted here.
"""

from __future__ import annotations

import pathlib
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

CAPTURE_SKILL = SKILLS / "flow-next-capture" / "SKILL.md"
CAPTURE_WORKFLOW = SKILLS / "flow-next-capture" / "workflow.md"
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
INTERVIEW_DOC_AWARE = (
    SKILLS / "flow-next-interview" / "references" / "doc-aware.md"
)
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-interview" / "references" / "write-back.md"
)

ALL_FILES = (
    CAPTURE_SKILL,
    CAPTURE_WORKFLOW,
    CAPTURE_PHASES,
    INTERVIEW_DOC_AWARE,
    INTERVIEW_WRITE_BACK,
)

# Old embed-in-body wording that made long drafts unreadable — must be gone.
# (Negative guards kept: embedding drafts in ask bodies is the dangerous class.)
FORBIDDEN_EMBED_PHRASES = (
    # Capture Phase 4 old ask body that listed every criterion inside the question.
    "Full draft in the Write render above (expand if collapsed)",
    "Every acceptance criterion's substance, one short plain line each",
    "the user must see what they are approving inside the question",
    # Interview decision-entry old allowance (explicit R13 target).
    "inline in the question or in the message preceding",
    "Show the full body inline in the question",
    # Old capture overview that put the summary payload / criteria in the ask.
    "the `AskUserQuestion` body carries the plain-language summary payload",
    "every criterion in one plain line",
    # fn-123 review hardening additions.
    "the question body must say the full draft is in the Write render above",
    "rides in the §4.2 question body",
)


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


class ReadbackAskContract(unittest.TestCase):
    """Print-then-ask tokens present; old long-question embed wording absent."""

    def setUp(self) -> None:
        for path in ALL_FILES:
            self.assertTrue(path.is_file(), f"missing canonical file: {path}")
        self.capture_skill = _read(CAPTURE_SKILL)
        self.capture_workflow = _read(CAPTURE_WORKFLOW)
        self.capture_phases = _read(CAPTURE_PHASES)
        self.doc_aware = _read(INTERVIEW_DOC_AWARE)
        self.write_back = _read(INTERVIEW_WRITE_BACK)
        self.combined = "\n".join(
            (
                self.capture_skill,
                self.capture_workflow,
                self.capture_phases,
                self.doc_aware,
                self.write_back,
            )
        )

    def test_contract_tokens_present_in_owning_files(self) -> None:
        for label, text in (
            ("capture/SKILL.md", self.capture_skill),
            ("capture/workflow.md", self.capture_workflow),
            ("capture/phases.md", self.capture_phases),
        ):
            with self.subTest(file=label):
                self.assertIn("print-then-ask", text)
        for label, text in (
            ("interview/references/doc-aware.md", self.doc_aware),
            ("interview/references/write-back.md", self.write_back),
        ):
            with self.subTest(file=label):
                self.assertIn("Print-then-ask", text)
        # Short-ask tally token + edit-cycle reprint token.
        self.assertIn("[inferred]", self.capture_workflow)
        self.assertIn("reprint", self.capture_workflow)
        self.assertIn("reprint", self.capture_phases)
        self.assertIn("reprint", self.doc_aware.lower())
        self.assertIn("reprint", self.write_back.lower())

    def test_old_embed_in_body_wording_absent(self) -> None:
        for phrase in FORBIDDEN_EMBED_PHRASES:
            with self.subTest(phrase=phrase):
                self.assertNotIn(
                    phrase,
                    self.combined,
                    f"old embed-in-ask-body wording still present: {phrase!r}",
                )

    def test_autofix_path_still_non_interactive(self) -> None:
        """Autofix remains non-interactive; --yes is still the consent substitute."""
        self.assertIn("mode:autofix", self.capture_skill)
        self.assertIn("--yes", self.capture_skill)
        self.assertRegex(
            self.capture_workflow,
            r"(?i)autofix.*--yes|`--yes`.*substitut",
        )


class TestPrintThenAskOrdering(unittest.TestCase):
    """fn-123 review hardening: assert ORDER, not just token presence.

    The §4.1 contract is a numbered sequence: print the full draft FIRST,
    then the short ask. Ordering keys on the smallest tokens (FULL draft /
    AskUserQuestion) inside the owning contract block.
    """

    def setUp(self) -> None:
        self.workflow = _read(CAPTURE_WORKFLOW)

    def _contract_block(self) -> str:
        start = self.workflow.find("Print-then-ask contract")
        self.assertGreater(
            start, -1, "capture workflow lost the print-then-ask contract block"
        )
        return self.workflow[start : start + 2500]

    def test_print_precedes_ask_in_contract_block(self) -> None:
        block = self._contract_block()
        print_pos = block.find("FULL draft")
        self.assertGreater(print_pos, -1, "contract lost the print-first step")
        # The ask step's AskUserQuestion mention must come AFTER the print step
        # (the intro sentence may mention the tool earlier; the step ordering is
        # what the fn-123 hardening guards).
        ask_pos = block.find("AskUserQuestion", print_pos)
        self.assertGreater(ask_pos, -1, "contract lost the short-ask step")


if __name__ == "__main__":
    unittest.main()
