"""Pre-flight gate + prose-contract tests for Codex implementation-delegation (fn-55.2).

The host-side pre-flight gates (platform gate + recursion guard) ship as runnable
bash inside ``references/codex-delegation.md``. They are pure shell predicates, so
this test EXTRACTS the two gate functions from the reference and EXECUTES them
under controlled env — the load-bearing acceptance criterion is that delegation
stays ELIGIBLE when ``CODEX_SANDBOX=auto`` is exported (Ralph's review-backend
knob) and that the recursion guard trips on a Codex RUNTIME value (e.g.
``seatbelt``) but not on ``auto``.

It also locks the prose contract — the progressive-disclosure value-check and the
disambiguation-from-the-review-backend tokens — across the canonical Claude
``SKILL.md`` / ``phases.md`` / reference (the Codex mirror is regenerated by
``sync-codex.sh`` in fn-55.6; this task ships the canonical side only).
"""

from __future__ import annotations

import os
import pathlib
import shutil
import subprocess
import sys
import unittest

# Gate-relevant env keys the tests control. We SCRUB these from the inherited OS
# env so only the per-test overrides decide eligibility — while keeping the rest
# of the env (PATH, and on Windows Git-bash SYSTEMROOT/WINDIR) so bash and the
# gate's `env | grep` actually run. A bare custom env strips those and breaks
# bash on Windows (every gate test fails rc=1). `OPENCODE_*` is matched by prefix.
_GATE_ENV_KEYS = (
    "CLAUDECODE",
    "CODEX_SANDBOX",
    "CODEX_SANDBOX_NETWORK_DISABLED",
    "DROID_PLUGIN_ROOT",
    "OPENCODE",
)


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
WORK_SKILL = REPO_ROOT / "plugins" / "flow-next" / "skills" / "flow-next-work"
SKILL_MD = WORK_SKILL / "SKILL.md"
PHASES_MD = WORK_SKILL / "phases.md"
REFERENCE_MD = WORK_SKILL / "references" / "codex-delegation.md"


def _extract_bash_func(text: str, func_name: str) -> str:
    """Pull a ``name() { ... }`` bash function body out of a fenced code block.

    The reference authors each gate as a shell function inside a ```bash fence.
    We extract by brace-matching from the function header so the test executes
    the EXACT shipped definition, not a paraphrase.
    """
    start = text.find(f"{func_name}() {{")
    if start == -1:
        raise AssertionError(f"bash function {func_name!r} not found in reference")
    depth = 0
    i = text.index("{", start)
    body_start = i
    while i < len(text):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return f"{func_name}() {text[body_start:i + 1]}"
        i += 1
    raise AssertionError(f"unbalanced braces extracting {func_name!r}")


@unittest.skipUnless(shutil.which("bash"), "bash required to execute gate predicates")
@unittest.skipIf(
    sys.platform == "win32",
    "POSIX-shell gate predicates: the host agent runs them under Git-bash, but "
    "executing the extracted multi-line predicate via a Python subprocess + a "
    "constructed env on the Windows runner tests bash plumbing, not gate logic. "
    "Fully exercised on macOS + ubuntu; the prose-contract tests run on Windows.",
)
class CodexDelegationGateExecution(unittest.TestCase):
    """Execute the shipped gate predicates under controlled env."""

    @classmethod
    def setUpClass(cls) -> None:
        # Normalize line endings to LF. On Windows the .md checks out CRLF (no
        # .gitattributes pins it to LF), so the extracted bash function would
        # carry trailing \r and `bash -c` fails to parse it ("syntax error near
        # unexpected token `{'") — every gate-execution test then returns
        # non-zero. Stripping \r makes the extracted predicate pure LF.
        cls.ref_text = (
            REFERENCE_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        cls.platform_fn = _extract_bash_func(cls.ref_text, "platform_gate_ok")
        cls.recursion_fn = _extract_bash_func(cls.ref_text, "not_inside_codex_sandbox")
        # The cheap Phase 0 host short-circuit lives in phases.md/SKILL.md (it must
        # resolve delegation OFF on a non-Claude host BEFORE the reference is read,
        # so it cannot live in the reference itself). Extract + execute the shipped
        # phases.md copy.
        phases_text = (
            PHASES_MD.read_text(encoding="utf-8")
            .replace("\r\n", "\n")
            .replace("\r", "\n")
        )
        cls.host_fn = _extract_bash_func(phases_text, "host_is_claude_code")

    def _run(self, func_def: str, call: str, env: dict) -> int:
        """Source the extracted function, call it, return its exit code."""
        script = f"set -u\n{func_def}\n{call}\n"
        # Start from a clean env so only the keys we set are present.
        # Inherit the OS env (PATH for bash + env/grep; SYSTEMROOT/WINDIR on
        # Windows Git-bash) but scrub every gate-relevant key first, then apply
        # the per-test overrides — so the env stays controlled without stripping
        # the vars bash needs to start.
        full_env = {
            k: v
            for k, v in os.environ.items()
            if k not in _GATE_ENV_KEYS and not k.startswith("OPENCODE_")
        }
        full_env.update(env)
        proc = subprocess.run(
            ["bash", "-c", script],
            env=full_env,
            capture_output=True,
            text=True,
        )
        return proc.returncode

    # ── Platform gate (rc 0 = eligible) ────────────────────────────────────

    def test_platform_gate_eligible_on_claude_code(self) -> None:
        rc = self._run(self.platform_fn, "platform_gate_ok", {"CLAUDECODE": "1"})
        self.assertEqual(rc, 0, "Claude Code (CLAUDECODE set, no Droid/OpenCode) must be eligible")

    # ── Phase 0 cheap host short-circuit (rc 0 = Claude Code = eligible) ────
    # The pre-LOAD gate: delegation must resolve OFF on a non-Claude host BEFORE
    # the ~45k reference is read into context (not just after, via Gate 1).

    def test_host_short_circuit_eligible_on_claude_code(self) -> None:
        rc = self._run(self.host_fn, "host_is_claude_code", {"CLAUDECODE": "1"})
        self.assertEqual(rc, 0, "Claude Code host must pass the cheap Phase 0 check")

    def test_host_short_circuit_off_without_claudecode(self) -> None:
        # The case this change targets: work.delegate=codex set, but work runs IN
        # Codex — CLAUDECODE unset → cheap check fails → reference never loaded.
        rc = self._run(self.host_fn, "host_is_claude_code", {})
        self.assertNotEqual(
            rc, 0, "non-Claude host (no CLAUDECODE) must short-circuit OFF pre-load"
        )

    def test_host_short_circuit_off_on_droid(self) -> None:
        rc = self._run(
            self.host_fn,
            "host_is_claude_code",
            {"CLAUDECODE": "1", "DROID_PLUGIN_ROOT": "/some/droid/root"},
        )
        self.assertNotEqual(rc, 0, "Droid must short-circuit OFF pre-load")

    def test_host_short_circuit_off_on_opencode(self) -> None:
        rc = self._run(
            self.host_fn, "host_is_claude_code", {"CLAUDECODE": "1", "OPENCODE": "1"}
        )
        self.assertNotEqual(rc, 0, "OpenCode must short-circuit OFF pre-load")

    def test_host_short_circuit_eligible_with_codex_sandbox_auto(self) -> None:
        # Ralph's review-backend knob must not flip the cheap host check.
        rc = self._run(
            self.host_fn,
            "host_is_claude_code",
            {"CLAUDECODE": "1", "CODEX_SANDBOX": "auto"},
        )
        self.assertEqual(
            rc, 0, "CODEX_SANDBOX=auto (Ralph knob) must leave the cheap host check ELIGIBLE"
        )

    def test_platform_gate_eligible_with_codex_sandbox_auto(self) -> None:
        # The load-bearing Ralph case: CODEX_SANDBOX=auto is the review-backend
        # knob, NOT a Codex-orchestrator signal. Platform gate must NOT exclude on it.
        rc = self._run(
            self.platform_fn,
            "platform_gate_ok",
            {"CLAUDECODE": "1", "CODEX_SANDBOX": "auto"},
        )
        self.assertEqual(
            rc, 0, "CODEX_SANDBOX=auto (Ralph knob) must leave the platform gate ELIGIBLE"
        )

    def test_platform_gate_off_without_claudecode(self) -> None:
        rc = self._run(self.platform_fn, "platform_gate_ok", {})
        self.assertNotEqual(rc, 0, "Missing CLAUDECODE → not Claude Code → ineligible")

    def test_platform_gate_off_on_droid(self) -> None:
        rc = self._run(
            self.platform_fn,
            "platform_gate_ok",
            {"CLAUDECODE": "1", "DROID_PLUGIN_ROOT": "/some/droid/root"},
        )
        self.assertNotEqual(rc, 0, "DROID_PLUGIN_ROOT set → Droid → ineligible")

    def test_platform_gate_off_on_opencode(self) -> None:
        rc = self._run(
            self.platform_fn,
            "platform_gate_ok",
            {"CLAUDECODE": "1", "OPENCODE": "1"},
        )
        self.assertNotEqual(rc, 0, "bare OPENCODE marker → ineligible")

    def test_platform_gate_off_on_prefixed_opencode_markers(self) -> None:
        # "AND no OpenCode marker" must cover arbitrary OPENCODE_* markers, not
        # just a fixed two-var check — OPENCODE_SESSION / OPENCODE_ROOT etc.
        for marker in ("OPENCODE_SESSION", "OPENCODE_ROOT", "OPENCODE_BIN"):
            with self.subTest(marker=marker):
                rc = self._run(
                    self.platform_fn,
                    "platform_gate_ok",
                    {"CLAUDECODE": "1", marker: "1"},
                )
                self.assertNotEqual(
                    rc, 0, f"{marker} (OpenCode marker) → ineligible"
                )

    # ── Recursion guard (rc 0 = NOT inside a sandbox = eligible) ────────────

    def test_recursion_guard_eligible_when_unset(self) -> None:
        rc = self._run(self.recursion_fn, "not_inside_codex_sandbox", {})
        self.assertEqual(rc, 0, "No CODEX_SANDBOX → not inside a sandbox → eligible")

    def test_recursion_guard_eligible_with_codex_sandbox_auto(self) -> None:
        # The load-bearing Ralph case again, on the recursion guard this time.
        rc = self._run(
            self.recursion_fn,
            "not_inside_codex_sandbox",
            {"CODEX_SANDBOX": "auto"},
        )
        self.assertEqual(
            rc, 0, "CODEX_SANDBOX=auto (config knob) must NOT trip the recursion guard"
        )

    def test_recursion_guard_eligible_with_config_set_values(self) -> None:
        for val in ("read-only", "workspace-write", "danger-full-access", "auto"):
            with self.subTest(value=val):
                rc = self._run(
                    self.recursion_fn,
                    "not_inside_codex_sandbox",
                    {"CODEX_SANDBOX": val},
                )
                self.assertEqual(
                    rc, 0, f"CODEX_SANDBOX={val} is in the flow-next config set → not a sandbox"
                )

    def test_recursion_guard_trips_on_runtime_value(self) -> None:
        rc = self._run(
            self.recursion_fn,
            "not_inside_codex_sandbox",
            {"CODEX_SANDBOX": "seatbelt"},
        )
        self.assertNotEqual(
            rc, 0, "CODEX_SANDBOX=seatbelt (Codex runtime value) must trip the recursion guard"
        )

    def test_recursion_guard_trips_on_network_disabled(self) -> None:
        rc = self._run(
            self.recursion_fn,
            "not_inside_codex_sandbox",
            {"CODEX_SANDBOX_NETWORK_DISABLED": "1"},
        )
        self.assertNotEqual(
            rc, 0, "CODEX_SANDBOX_NETWORK_DISABLED set must trip the recursion guard"
        )


class CodexDelegationProseContract(unittest.TestCase):
    """Lock the progressive-disclosure + disambiguation prose contract."""

    @classmethod
    def setUpClass(cls) -> None:
        for p in (SKILL_MD, PHASES_MD, REFERENCE_MD):
            assert p.exists(), f"missing required file: {p}"
        cls.skill = SKILL_MD.read_text(encoding="utf-8")
        cls.phases = PHASES_MD.read_text(encoding="utf-8")
        cls.ref = REFERENCE_MD.read_text(encoding="utf-8")

    def test_reference_exists_with_preflight_section(self) -> None:
        self.assertIn("Host pre-flight gates", self.ref)
        # Section stubs for the downstream tasks must be present (scaffold contract).
        self.assertIn("fn-55.3", self.ref)
        self.assertIn("fn-55.4", self.ref)
        self.assertIn("fn-55.5", self.ref)

    def test_phases_default_path_adds_single_value_check(self) -> None:
        # The one cheap value-check is the only thing added to the default path.
        self.assertIn("config get work.delegate", self.phases)
        # And it is explicitly framed as the ONLY added step.
        self.assertRegex(self.phases, r"ONLY step|single step|byte-identical")

    def test_skill_disambiguates_delegate_token_from_review_backend(self) -> None:
        for token in ("delegate:codex", "delegate:local", "work.delegate=codex"):
            with self.subTest(token=token):
                self.assertIn(token, self.skill)
        # Must state bare "use codex" stays the review backend (not delegation).
        self.assertIn("use codex", self.skill)
        self.assertRegex(self.skill, r"review backend|review-backend")

    def test_skill_points_to_reference(self) -> None:
        self.assertIn("references/codex-delegation.md", self.skill)
        self.assertIn("references/codex-delegation.md", self.phases)

    def test_phase0_host_short_circuit_documented(self) -> None:
        # Delegation is Claude-Code-only and the cheap Phase 0 check must gate
        # delegation_active so the reference is NEVER read on a non-Claude host
        # (Codex / Droid / OpenCode). Both host skill files carry the check, ANDed
        # into the predicate; the reference header states it is not read there.
        for src in (self.phases, self.skill):
            self.assertIn("host_is_claude_code", src)
            self.assertRegex(src, r"host_is_claude_code\s*&&")
        self.assertIn("never read into context", self.ref)

    def test_input_bare_prompt_capture_documented(self) -> None:
        self.assertIn("INPUT_WAS_BARE_PROMPT", self.phases)
        self.assertIn("INPUT_WAS_BARE_PROMPT", self.ref)

    def test_consent_lives_in_host_not_worker(self) -> None:
        # Consent must be in the host skill files (SKILL.md/phases.md) and the
        # reference must say it is host-side (the worker can't AskUserQuestion).
        self.assertIn("AskUserQuestion", self.phases)
        self.assertIn("work.delegateConsent", self.ref)
        self.assertIn("work.delegateSandbox", self.ref)
        # The "#12890/#34592" worker-cant-ask rationale is preserved.
        self.assertIn("#12890", self.ref)

    def test_platform_gate_not_keyed_on_codex_env(self) -> None:
        # The reference must explicitly warn NOT to exclude on CODEX_* and call
        # out that CODEX_SANDBOX=auto is the review-backend knob.
        self.assertRegex(self.ref, r"Do NOT exclude on .?CODEX_\*")
        self.assertIn("CODEX_SANDBOX=auto", self.ref)

    def test_recursion_guard_config_set_documented(self) -> None:
        # The flow-next config set must be enumerated so the runtime-vs-config
        # distinction is unambiguous.
        for mode in ("read-only", "workspace-write", "danger-full-access", "auto"):
            with self.subTest(mode=mode):
                self.assertIn(mode, self.ref)
        self.assertIn("CODEX_SANDBOX_NETWORK_DISABLED", self.ref)

    def test_headless_ralph_consent_rule_documented(self) -> None:
        # Headless proceeds only if consent already granted; no AskUserQuestion.
        self.assertRegex(self.ref, r"Headless.*Ralph|FLOW_RALPH|REVIEW_RECEIPT_PATH")
        self.assertRegex(self.ref, r"silently off|stays.*off|delegation.*off")

    def test_delegate_decision_semantics_documented(self) -> None:
        self.assertIn("work.delegateDecision", self.ref)
        self.assertIn("auto", self.ref)
        self.assertIn("ask", self.ref)


if __name__ == "__main__":
    unittest.main()
